actions: coverage
cylc/cylc-flow pull request #3923
Opened 2020-11-05 15:52 UTC by oliver-sanders

closes: #3598
follow on from: #3899

Reinstates code coverage for Cylc.

It does:

* Capture all `cylc` commands.
* Write the coverage files in your Cylc working directory.
* Work for remote platforms (though you will have to copy back the coverage files manually).

It does not:

* Capture coverage for direct access to the `cylc` library from Python (i.e. not via the `cylc` CLI).
    * For this you can use standard tools directly (`coverage`, `pytest --cov`, etc).
* Capture anything after the daemonisation (i.e. when `--no-detach` is *not* set).
    * Can be done in the future though there is little to gain from doing so.

**Requirements check-list**
- [ ] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [ ] Contains logically grouped changes (else tidy your branch by rebase).
- [ ] Does not contain off-topic changes (use other PRs for other changes).

- [ ] Appropriate tests are included (unit and/or functional).
- [ ] Already covered by existing tests.
- [ ] Does not need tests (why?).

- [ ] Appropriate change log entry included.
- [ ] No change log entry required (why? e.g. invisible to users).

- [ ] (master branch) I have opened a documentation PR at cylc/cylc-doc/pull/XXXX.
- [ ] (7.8.x branch) I have updated the documentation in this PR branch.
- [ ] No documentation update required.

- [ ] Created an issue at [cylc-flow conda-forge repository](https://github.com/conda-forge/cylc-flow-feedstock) with version changes (if you changed dependencies in `setup.py`, see `recipe/meta.yaml`).
- [ ] No dependency changes.

2020-11-10 19:22 UTC, oliver-sanders commented
This should get that test run on the right platform:

```
diff --git a/tests/functional/remote/04-symlink-dirs.t b/tests/functional/remote/04-symlink-dirs.t
index 1e343d709..bb706cbf3 100644
--- a/tests/functional/remote/04-symlink-dirs.t
+++ b/tests/functional/remote/04-symlink-dirs.t
@@ -17,8 +17,8 @@
 #-------------------------------------------------------------------------------
 # Checks configured symlinks are created for run, work, share, share/cycle, log 
 # # directories on localhost and the remote platform.
-. "$(dirname "$0")/test_header"
 export REQUIRE_PLATFORM='loc:remote comms:tcp'
+. "$(dirname "$0")/test_header"
 
 if [[ -z ${TMPDIR:-} || -z ${USER:-} || $TMPDIR/$USER == "$HOME" ]]; then
```

2020-12-30 11:21 UTC, oliver-sanders commented
Deconflicted

2020-12-30 12:51 UTC, MetRonnie commented on cylc/flow/scripts/cylc.py
> +    $ ssh remote-host cd /cylc/remote/working/directory && covrage combine
Typo
```suggestion
    $ ssh remote-host cd /cylc/remote/working/directory && coverage combine
```

2020-12-30 12:53 UTC, MetRonnie commented on cylc/flow/scripts/cylc.py
> +    cylc_wc = Path(cylc.flow.__file__).parent.parent.parent
```suggestion
    cylc_wc = Path(cylc.flow.__file__).parents[2]
```
https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.parents

2020-12-30 12:55 UTC, MetRonnie commented
`tests/unit/main_loop/auto_restart.py → tests/unit/main_loop/test_auto_restart` has lost its extension

2020-12-30 12:57 UTC, MetRonnie requested changes
`tests/unit/main_loop/auto_restart.py → tests/unit/main_loop/test_auto_restart` has lost its extension. Other suggestions optional

2020-12-30 14:06 UTC, oliver-sanders commented on cylc/flow/scripts/cylc.py
> +    $ ssh remote-host cd /cylc/remote/working/directory && covrage combine
Well spotted.

2020-12-30 14:06 UTC, oliver-sanders commented on cylc/flow/scripts/cylc.py
> +    cylc_wc = Path(cylc.flow.__file__).parent.parent.parent
Nice

2020-12-30 14:58 UTC, MetRonnie approved these changes

2020-12-30 22:35 UTC, kinow approved these changes

2020-12-30 22:35 UTC, kinow commented on cylc/flow/scripts/cylc.py
> +                execute_cmd(command, *cmd_args)
:clap: great workaround !

2020-12-31 08:50 UTC, merged