Fix param expansion in inherited environment.
cylc/cylc-flow pull request #4248
Opened 2021-06-08 04:52 UTC by hjoliver

These changes close #4242 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] No dependency changes. 

- [ ] Appropriate tests are included (unit and/or functional).
- [ ] Already covered by existing tests.
- [ ] Does not need tests (why?).

- [ ] Appropriate change log entry included.
- [ ] No change log entry required (why? e.g. invisible to users).

- [x] No documentation update required (this branch conforms to advertised behaviour).

2021-06-08 23:41 UTC, hjoliver commented
This is ready to go now.

2021-06-09 00:09 UTC, kinow approved these changes
Code and tests look good! Pending only CI to pass :+1:

2021-06-09 01:45 UTC, kinow commented
mypy error fixed in the merged #4251

2021-06-09 01:49 UTC, hjoliver commented
Rebased.

2021-06-09 02:15 UTC, kinow commented
@hjoliver can we ignore the macos failure?

```
2021-06-09T01:59:36.3004720Z TOTAL                                                20623   7211   8643      0    75.36%
2021-06-09T01:59:36.3005000Z 
2021-06-09T01:59:36.3005400Z =========================== short test summary info ============================
2021-06-09T01:59:36.3006860Z FAILED tests/integration/test_scan.py::test_scan_sigstop - AssertionError: as...
2021-06-09T01:59:36.3007580Z ================== 1 failed, 86 passed, 24 warnings in 33.58s ==================
```

```
2021-06-09T01:59:36.2794800Z E           AssertionError: assert [(20, '[one.1...05056910e93')] == [(30, 'Workfl...05056910e93')]
2021-06-09T01:59:36.2796570Z E             At index 0 diff: (20, '[one.1] -released from runahead') != (30, 'Workflow not running: 46dcaa6a-c8c6-11eb-8e68-005056910e93')
2021-06-09T01:59:36.2798370Z E             Left contains one more item: (30, 'Workflow not running: 46dcaa6a-c8c6-11eb-8e68-005056910e93')
2021-06-09T01:59:36.2799580Z E             Full diff:
2021-06-09T01:59:36.2800190Z E               [
2021-06-09T01:59:36.2800750Z E             +  (20,
2021-06-09T01:59:36.2801840Z E             +   '[one.1] -released from runahead'),
2021-06-09T01:59:36.2802600Z E                (30,
2021-06-09T01:59:36.2803850Z E                 'Workflow not running: 46dcaa6a-c8c6-11eb-8e68-005056910e93'),
2021-06-09T01:59:36.2804740Z E               ]
```

2021-06-09 02:16 UTC, hjoliver commented
Yeah that MacOS scan test is failing on most PRs now, nothing to do with this change.  Ping @oliver-sanders

2021-06-09 02:21 UTC, kinow approved these changes

2021-06-09 23:05 UTC, kinow approved these changes

2021-06-09 23:05 UTC, kinow commented on cylc/flow/config.py
> +                            )
:+1:

2021-06-11 09:23 UTC, oliver-sanders requested changes
Sadly this didn't work for my example workflow, took a bit of staring before I found the edge case that was causing the bug.

On this branch the following example fails:

```ini
[task parameters]
    a = 1..3
    b = 1

[scheduling]
    [[graph]]
        R1 = x<b>

[runtime]
    [[FAM<a>]]
        [[[environment]]]
            param = %(a)s

    [[x<b=1>]]
        inherit = FAM<a=1>
        script = test $param -eq 1

    [[x<b>]]
        pre-script = echo pre
```

However, if you comment out the last task:

```
    # [[x<b>]]
    #    pre-script = echo pre
```

It will pass on this branch (but not on master).

2021-06-11 22:51 UTC, hjoliver commented
God damn it. Sadly indeed!

2021-06-11 23:14 UTC, hjoliver commented
It certainly works for your original example, on #4242

2021-06-11 23:27 UTC, hjoliver commented
Interestingly, it works if I swap the order:
```
    [[x<b>]]
        pre-script = echo pre

    [[x<b=1>]]
        inherit = FAM<a=1>
        script = test $param -eq 1
```

2021-06-12 01:01 UTC, hjoliver commented
Fixed now, and test extended to cover this case.

2021-06-14 14:08 UTC, oliver-sanders approved these changes
My example now passes, thanks.

2021-06-14 14:09 UTC, merged