[WIP] Move tutorials
cylc/cylc-flow pull request #4561
Opened 2021-12-21 11:49 UTC by wxtim

These changes partially address #xxxx
These changes close #xxxx
This is a small change with no associated Issue.

**Requirements check-list**
- [ ] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [ ] Contains logically grouped changes (else tidy your branch by rebase).
- [ ] Does not contain off-topic changes (use other PRs for other changes).
- [ ] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.

- [ ] Appropriate tests are included (unit and/or functional).
- [ ] Already covered by existing tests.
- [ ] Does not need tests (why?).

- [ ] Appropriate change log entry included.
- [ ] No change log entry required (why? e.g. invisible to users).

- [ ] (master branch) I have opened a documentation PR at cylc/cylc-doc/pull/XXXX.
- [ ] (7.8.x branch) I have updated the documentation in this PR branch.
- [ ] No documentation update required.

2022-01-07 16:47 UTC, MetRonnie commented on .github/actions/install-dependencies/action.yml
> +name: Install dependencies
No need to copy this action here, can just use like so
```yaml
- name: Install docs/tutorial dependencies
  uses: cylc/cylc-doc/.github/actions/install-dependencies@master
```

2022-01-07 16:52 UTC, MetRonnie commented on .github/workflows/test_tutorial_workflow.yml
> +        uses: actions/checkout@v2
```suggestion
      - name: checkout
        uses: actions/checkout@v2
```

2022-01-07 16:52 UTC, MetRonnie commented on .github/workflows/test_tutorial_workflow.yml
> +        uses: ./.github/actions/install-dependencies
See my earlier comment
```suggestion
      - name: Install docs/tutorial dependencies
        uses: cylc/cylc-doc/.github/actions/install-dependencies@master
```

2022-01-07 16:52 UTC, MetRonnie commented on .github/workflows/test_tutorial_workflow.yml
> +      - name: install cylc-doc
```suggestion
      - name: install cylc-flow
```

2022-01-10 09:25 UTC, wxtim commented
Test failures look like those fixed in #4574

2022-01-10 10:02 UTC, MetRonnie approved these changes

2022-01-13 03:49 UTC, hjoliver requested changes
Can `bin/run-validate` be a) renamed to makes its purpose clear, e.g. `run-validate-tutorials`; and b) moved to `etc/bin/`where the other developer scripts live? (it seems a weird thing to have as the sole resident of a top-level bin directory in the cylc-flow repo)

2022-01-13 10:42 UTC, MetRonnie requested changes
Also changelog in conflict at the moment

2022-01-13 10:42 UTC, MetRonnie commented on etc/bin/run-validate-tutorials
> +for FILE in $(echo ../cylc/flow/etc/tutorial/*/.validate) ; do
This path looks like it needs updating
```
running ../cylc/flow/etc/tutorial/*/.validate
etc/bin/run-validate-tutorials: line 25: cd: ../cylc/flow/etc/tutorial/*: No such file or directory
```
https://github.com/cylc/cylc-flow/runs/4799870817?check_suite_focus=true#step:7:8

2022-01-13 14:02 UTC, MetRonnie approved these changes

2022-01-13 22:22 UTC, hjoliver approved these changes

2022-01-13 22:22 UTC, merged