validate: move seqence bounds validation into the config
cylc/cylc-flow pull request #4592
Opened 2022-01-19 14:05 UTC by oliver-sanders

* `cylc play` should do more or less everything `cylc validate` does.
* The sequence bounds check was only being run for `cylc validate`.
* This moves the logic into `cylc.flow.config` so it is run for both
  `cylc validate` and `cylc play`.
* Already tested by tests/functional/validate/71-task-proxy-sequence-bounds-err.t

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [x] Already covered by existing tests.
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.

2022-01-24 16:40 UTC, wxtim requested changes
- [x] Read the code.
- [x] Played with code, added breakpoints. 
- [x] Manually tested the described behavior

The test you refer to (`f/validate/71-...`) may not be sufficient to test this change: It only tests whether this function is called & logs a warning for validate - If it's being used as a proxy unit test it's OK, but can we create a ticket to make it a Python unit test. If it's being used as a functional test shouldn't it check that Cylc Play actually uses the function?

2022-01-24 16:52 UTC, wxtim commented
> This PR moves a bit of validate logic into the config so that it is performed automatically every time the config is loaded rather than only for the `validate` command.

I'm confident that this is what is happening, but I had to manually test it to assure myself that it _was_ called by ``cylc play``, which I thought was the main point of the change.

> I'm not sure how a Python unit test would help here, it would check the expected warning is logged the same way the functional test would?

It'd do the same job faster and more read-ably.

2022-01-24 17:00 UTC, oliver-sanders commented
> I'd like more test

What aspect of this feature do you think is not covered by the pre-existing tests?

2022-01-24 17:01 UTC, wxtim commented
> > I'd like more test
> 
> What aspect of this feature do you think is not covered by the pre-existing tests?

I don't think that you have tested whether this warning will be logged if you run and command other than ``cylc validate``. From what you are saying I think that's probably OK.

2022-01-25 00:29 UTC, hjoliver approved these changes
Failing flaky test unrelated; passes locally.

I think this can go in as-is.

The function is unit testable, but we do have loads of functional validation tests, and they are fast for functional tests, so no biggie. (Plus, I guess we should test that these methods are used via the cli commands).

2022-01-25 16:11 UTC, wxtim approved these changes
I agree with @hjoliver  that this is ready to merge.

2022-01-25 16:11 UTC, merged