scheduler events: add back support for "suite"
cylc/cylc-flow pull request #4724
Opened 2022-03-01 17:10 UTC by oliver-sanders

The "suite" argument is missing from the message context used for scheduler events.

We've supported it in other contexts so should probably do so here too.

2022-03-01 20:10 UTC, hjoliver approved these changes
Thanks, good spot.

2022-03-01 20:23 UTC, hjoliver reviewed
Although, this whole block should be converted to use `EventData.Suite.value` etc.?

2022-03-07 04:03 UTC, hjoliver commented
Tests not happy.

2022-03-07 04:03 UTC, hjoliver requested changes
(Just un-approving for clarity, since the scope widened)

2022-03-10 09:31 UTC, oliver-sanders commented
(straightening out some further inconsistencies)

2022-03-29 14:27 UTC, oliver-sanders commented
Rebased.

2022-03-31 02:59 UTC, hjoliver approved these changes
Just a few minor grammar issues.

2022-03-31 02:59 UTC, hjoliver commented on cylc/flow/task_events_mgr.py
> +    The number of execution attempts, starts at 1, increments with automatic
```suggestion
    The number of execution attempts. It starts at 1 and increments with automatic
```

2022-03-31 02:59 UTC, hjoliver commented on cylc/flow/task_events_mgr.py
> +    I.E. The job submission ID, for background jobs this is the process ID.
```suggestion
    I.E. The job submission ID. For background jobs this is the process ID.
```

2022-03-31 02:59 UTC, hjoliver commented on cylc/flow/task_events_mgr.py
> +    """Date-time when the job was submitted in ISO8601 format."""
```suggestion
    """Date-time when the job was submitted, in ISO8601 format."""
```

2022-03-31 02:59 UTC, hjoliver commented on cylc/flow/task_events_mgr.py
> +    """Date-time when the job started in ISO8601 format."""
```suggestion
    """Date-time when the job started, in ISO8601 format."""
```

2022-03-31 02:59 UTC, hjoliver commented on cylc/flow/task_events_mgr.py
> +    """Date-time when the job finished in ISO8601 format."""
```suggestion
    """Date-time when the job finished, in ISO8601 format."""
```

2022-03-31 12:53 UTC, wxtim commented on tests/integration/events/test_workflow_events.py
> +@pytest.mark.parametrize('template', TEMPLATES)
Might use this way of storing parameters since it seems to me easier to read.

2022-03-31 13:09 UTC, wxtim commented on cylc/flow/task_events_mgr.py
> +    :cylc:conf:`flow.cylc[runtime][<namespace>]execution retry delays`.
```suggestion
    The number of execution attempts.
    It starts at 1 and increments with automatic
    :cylc:conf:`flow.cylc[runtime][<namespace>]execution retry delays`.
```

2022-03-31 23:48 UTC, hjoliver commented
2 approvals, tests all pass (except the usual macos timeout)

2022-03-31 23:49 UTC, merged