Flow triggers 2/2: --wait via the DB
cylc/cylc-flow pull request #4739
Opened 2022-03-14 08:52 UTC by hjoliver

These changes close #4686

Built on top off #4738 `<---` merge that sucker first

Implement `--wait` delayed merge flow triggering.

TBD:
- currently spawns on all outputs of the triggered task on continuing the flow; load actual completed outputs and spawn on them
- make it work even if the same task is triggered multiple times

**Requirements check-list**
- [ ] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [ ] Contains logically grouped changes (else tidy your branch by rebase).
- [ ] Does not contain off-topic changes (use other PRs for other changes).
- [ ] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.

- [ ] Appropriate tests are included (unit and/or functional).

- [ ] Appropriate change log entry included.

- [ ] (master branch) I have opened a documentation PR at cylc/cylc-doc/pull/XXXX.

2022-03-21 04:34 UTC, hjoliver commented
Fast tests will fail till #4746 goes in.

2022-03-22 09:23 UTC, hjoliver commented
This fixes and extends the DB `task_outputs` table. On master, the table holds only custom outputs, for the most recent submit of each task. Here, it holds all outputs, with flow numbers. E.g.:

```console
$ sqlite3 -header ~/cylc-run/ft/runN/log/db "select * from task_outputs;"
cycle|name|flow_nums|outputs
1|foo|[1]|["submitted", "started", "succeeded"]
1|bar|[1]|["submitted", "started", "the quick brown fox", "succeeded"]
1|baz|[1]|["submitted", "started", "failed"]
```
For repeat-running a task *in the same flow* via `cylc trigger --wait` we care about outputs from the most recent run in the right flow, not necessarily the most recent submit.  So at this stage I don't think it's necessary to add submit number to the table as well.

2022-03-22 10:28 UTC, hjoliver commented
(One last TODO for tomorrow: correctly handle `n=0` flow merge with a still-running `trigger --wait` task)

2022-04-04 00:41 UTC, hjoliver commented
(Rebased and deconflicted)

2022-04-06 05:09 UTC, hjoliver commented
>Here's a PR that adds a default value to the flow arg to allow tui to work with the mutation:

Thanks, merged!

2022-04-06 10:16 UTC, oliver-sanders reviewed
Most the way through.

2022-04-06 10:16 UTC, oliver-sanders commented on cylc/flow/task_pool.py
> +                    flow_nums = {int(n) for n in flow}
I think this gets pre-validated(?) but should still probably still stick this in a try/except for safety as a ValueError here would tear down the workflow.

2022-04-06 10:16 UTC, oliver-sanders commented on cylc/flow/task_pool.py
> +                # TODO PUT THESE IN TASK INIT
TODO

2022-04-10 23:02 UTC, hjoliver commented on cylc/flow/task_pool.py
>                      self.data_store_mgr.delta_task_output(itask, message)
No. On master, we store both the label and the message for custom outputs.  On this branch, just the message.

2022-04-11 01:06 UTC, hjoliver commented
Feedback addressed.

2022-04-11 07:20 UTC, dwsutherland commented
> > Here's a PR that adds a default value to the flow arg to allow tui to work with the mutation:
> 
> Thanks, merged!

Doesn't look like it's merged..

2022-04-11 07:31 UTC, hjoliver commented
> > > Here's a PR that adds a default value to the flow arg to allow tui to work with the mutation:
> > 
> > 
> > Thanks, merged!
> 
> Doesn't look like it's merged..

Oops, good spot. It is now. I must have been waiting for tests or something.

2022-04-11 07:38 UTC, hjoliver commented
Imported a flake8-bugbear error from @oliver-sanders side-PR:
> ./cylc/flow/network/schema.py:1410:5: B021 f-string used as docstring.This will be interpreted by python as a joined string rather than a docstring.

2022-04-11 07:38 UTC, hjoliver commented
(OK you bet me to it :-)

2022-04-11 07:39 UTC, hjoliver commented
Rebased.

2022-04-11 10:56 UTC, hjoliver commented
(Damn it, tests all passed before I merged that side PR and rebased!)

2022-04-12 02:01 UTC, hjoliver commented
> Imported a flake8-bugbear error from @oliver-sanders side-PR:
> 
> > ./cylc/flow/network/schema.py:1410:5: B021 f-string used as docstring.This will be interpreted by python as a joined string rather than a docstring.

FYI @oliver-sanders (and others) - doc-strings cannot be f-strings:

https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals

2022-04-12 03:50 UTC, hjoliver commented
All fixed :tada:

2022-04-12 05:36 UTC, dwsutherland approved these changes
Looks good to me:
- Worked in my environment.
- Tests passed.
- Code is fine.

👍

2022-04-12 10:53 UTC, oliver-sanders commented
> FYI @oliver-sanders (and others) - doc-strings cannot be f-strings:

TIL. You can modify, format or even replace a docstring after it has been declared, however, you cannot do so at the time of declaration.

```python
FOO = 42


class Modified:
    '{FOO}'
    

Modified.__doc__ = Modified.__doc__.format(**globals())


class FString:
    f'''{FOO}'''
    
    
class Format:
    '''{FOO}'''.format(**globals())


# this works
print(Modified.__doc__)

# these don't
print(FString.__doc__)
print(Format.__doc__)
```

```console
$ python mess.py 
42
None
None
```

2022-04-12 15:25 UTC, oliver-sanders requested changes
Completed functional review, all good except one bug which can cause multiple new flows to be created for a single trigger `--flow=new` event.

Put up a fix: https://github.com/hjoliver/cylc-flow/pull/22

Otherwise good!

2022-04-12 23:26 UTC, hjoliver commented on cylc/flow/network/schema.py
> +    """An integer or one of {FLOW_ALL}, {FLOW_NEW} or {FLOW_NONE}."""
We can't expand them, or the docstring ceases to be a docstring (see my comment on that).

I think it's fine to leave like that. Docstrings describe code, so it's not unreasonable for them to refer to variable (or constant) names. I should perhaps have removed the braces, but I added to comment to note that it shouldn't be turned back into an f-string.

2022-04-13 08:39 UTC, oliver-sanders approved these changes
:tada:

Thanks @hjoliver this has been a fun one!

2022-04-13 08:39 UTC, merged

2022-04-13 20:24 UTC, hjoliver commented
> tada
> 
> Thanks @hjoliver this has been a fun one!

Heheh, yes it has :rofl: 

:tada: