Db upgrade 8.0.3
cylc/cylc-flow pull request #5187
Opened 2022-10-10 22:03 UTC by hjoliver

Follow-up #5023 
Supersede #5173 

Automatically upgrade pre-8.0.3 DBs by adding the new task_states "is_manual_submit" column.

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [ ] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [ ] If this is a bug fix, PRs raised to both master and the relevant maintenance branch.

2022-10-11 01:46 UTC, hjoliver commented
Integration test added.

2022-10-11 08:07 UTC, oliver-sanders approved these changes

2022-10-11 09:51 UTC, MetRonnie requested changes
I have opened a PR against this with some fixes, including ensuring the DAO is closed: https://github.com/hjoliver/cylc-flow/pull/26

2022-10-11 13:45 UTC, MetRonnie approved these changes
Tested, working

2022-10-11 13:45 UTC, MetRonnie commented on CHANGES.md
> + - tasks force-triggered
Just to avoid having an odd bullet point
```suggestion
[#5187](https://github.com/cylc/cylc-flow/pull/5187) -
tasks force-triggered
```

2022-10-12 00:02 UTC, hjoliver commented
I don't think we need to bother @oliver-sanders with a re-review (he approved before the tweaks).

2022-10-12 00:02 UTC, merged