id: perserve selectors for "task" and "workflow" properties
cylc/cylc-flow pull request #5188
Opened 2022-10-11 09:30 UTC by oliver-sanders

* Selectors were not correctly preserved for the `task` and `workflow` properties of `Tokens` objects.
* This effectively stripped cycle/task selectors from IDs passed to `cylc trigger`.
* Closes https://github.com/cylc/cylc-flow/issues/5186

**Check List**

- [ ] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [ ] Contains logically grouped changes (else tidy your branch by rebase).
- [ ] Does not contain off-topic changes (use other PRs for other changes).
- [ ] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [ ] Tests are included (or explain why tests are not needed).
- [ ] `CHANGES.md` entry included if this is a change that can affect users
- [ ] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [ ] If this is a bug fix, PRs raised to both master and the relevant maintenance branch.

2022-10-12 23:32 UTC, hjoliver approved these changes
:+1: LGTM

2022-10-12 23:42 UTC, hjoliver reviewed
Doesn't fix the original reported problem...

2022-10-13 00:54 UTC, hjoliver requested changes
OK, to close the issue we need to detokenise IDs with `selectors=True` in the CLI scripts.  I'll post a PR to your branch.

2022-10-13 14:50 UTC, MetRonnie approved these changes

2022-10-13 15:48 UTC, MetRonnie approved these changes

2022-10-13 21:53 UTC, hjoliver approved these changes

2022-10-13 21:53 UTC, hjoliver commented on CHANGES.md
> +Fix task state selectors in the `cylc trigger` command.
```suggestion
Fix task state selectors in `cylc trigger` and other commands.
```

2022-10-13 21:54 UTC, merged