Turn log timestamps back on before running Cylc Play in VIP & VR
cylc/cylc-flow pull request #5524
Opened 2023-05-05 20:28 UTC by wxtim

Closes #5505

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [ ] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) entry not req'd
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

2023-05-08 01:06 UTC, hjoliver requested changes
Looks good. One minor issue, it would be slightly cleaner to have a single `toggle_timestamps` function?

2023-05-09 09:34 UTC, wxtim commented
> Looks good. One minor issue, it would be slightly cleaner to have a single `toggle_timestamps` function?

Sort of - my only concern is that for me the word "toggle" means "get the state and change it to the other state". Whilst this function could do this, I think it's better if it specifies the desired state to avoid ambiguity. To this end I've made the `enable` argument compulsory, because I think defaulting to `True` is misleading.

2023-05-09 16:27 UTC, MetRonnie commented on cylc/flow/loggingutil.py
> +def toggle_timestamps(logger: logging.Logger, enable: bool) -> None:
`set_timestamps` would be a more appropriate name imho

2023-05-09 16:27 UTC, MetRonnie commented on cylc/flow/scripts/validate_install_play.py
> +    toggle_timestamps(LOG, True)
Still need to respect CLI option
```suggestion
    toggle_timestamps(LOG, options.log_timestamp)
```

2023-05-09 16:27 UTC, MetRonnie commented on cylc/flow/scripts/validate_reinstall.py
> +        toggle_timestamps(LOG, True)
```suggestion
        toggle_timestamps(LOG, options.log_timestamp)
```

2023-05-10 00:12 UTC, hjoliver commented
> Sort of - my only concern is that for me the word "toggle" means "get the state and change 

Yes, badly chosen word sorry. I really meant something like `set_timestamps(state=bool)` - i.e. one function but you do have to specify the desired state, not just "toggle" to the other state whatever that is.

2023-05-11 12:22 UTC, hjoliver approved these changes
👍

2023-05-11 12:22 UTC, merged