config: validate task messages and outputs
cylc/cylc-flow pull request #5606
Opened 2023-06-28 16:22 UTC by oliver-sanders

* Task messages & outputs should be validated to avoid users shadowing built-in messages, outputs or qualifiers.
* Reserve the `_cylc` prefix save we need it later.

Also reserve the outputs `required`, `optional` and `all` as keywords for future use by `cylc set`, see [cylc set proposal](https://github.com/cylc/cylc-admin/pull/173). This proposal isn't approved yet and won't be implemented until Cylc 8.3.0, however, we may as well reserve these keywords now as the proposal will not change their meaning.

I've checked workflows at our end and have found shockingly little usage of custom outputs and no obvious breakages as a result of these changes.

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [ ] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

2023-06-28 16:27 UTC, oliver-sanders commented on CHANGES.md
> +[#5605](https://github.com/cylc/cylc-flow/pull/5605) -
```suggestion
[#5606](https://github.com/cylc/cylc-flow/pull/5606) -
```

2023-06-29 00:03 UTC, hjoliver approved these changes
V. nice 👍

2023-06-29 00:03 UTC, hjoliver commented on tests/integration/validate/test_outputs.py
> +        print(output)
```suggestion
```

(Debugging?)

2023-06-29 00:03 UTC, hjoliver commented on tests/integration/validate/test_outputs.py
> +        print(message)
```suggestion
```
(Debugging?)

2023-06-29 15:59 UTC, MetRonnie commented on CHANGES.md
> +[#5605](https://github.com/cylc/cylc-flow/pull/5605) -
Are you going to apply this?

2023-06-29 16:03 UTC, oliver-sanders commented on CHANGES.md
> +[#5605](https://github.com/cylc/cylc-flow/pull/5605) -
Yep, waiting for reviews.

2023-06-30 10:52 UTC, MetRonnie requested changes

2023-06-30 10:52 UTC, MetRonnie commented on cylc/flow/unicode_rules.py
> +        f'cannot be: {formatted}'
D'oh I made a mess of this the first time round
```suggestion
        'cannot be: ' + _human_format_list([f'``{s}``' for s in strings])
```

2023-07-03 14:56 UTC, MetRonnie approved these changes

2023-07-04 10:12 UTC, merged