doc: clarify runahead limit
cylc/cylc-flow pull request #5754
Opened 2023-10-04 09:11 UTC by oliver-sanders

The "consecutive" terminology can be a little confusing.

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at [cylc/cylc-doc/pull/XXXX.](https://github.com/cylc/cylc-doc/pull/660)
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

2023-10-05 16:34 UTC, dpmatthews requested changes

2023-10-05 16:34 UTC, dpmatthews commented on cylc/flow/cfgspec/workflow.py
> +            value instead, in which case the number of active cycles
"number of cycles" maybe better - they don't have to be active

2023-10-09 09:04 UTC, oliver-sanders commented on cylc/flow/cfgspec/workflow.py
> +            value instead, in which case the number of active cycles
```suggestion
            value instead, in which case the number of cycles
```

2023-10-11 06:27 UTC, dpmatthews requested changes

2023-10-11 06:27 UTC, dpmatthews commented on cylc/flow/cfgspec/workflow.py
> +            :term:`active` or :term:`incomplete` tasks.
See https://github.com/cylc/cylc-doc/pull/660. We need a consistent way to describe this.

2023-10-17 00:08 UTC, hjoliver approved these changes
Approved, assuming "active cycles" will soon be properly defined in the glossary.

2024-04-29 22:46 UTC, hjoliver commented
Let's get this into 8.3.0

2024-04-29 22:48 UTC, merged