Feat.lint obsolete vars
cylc/cylc-flow pull request #5879
Opened 2023-12-14 11:03 UTC by wxtim

Another item from Oliver's wishlist at https://github.com/cylc/cylc-flow/issues/4917:

Search for deprecated items from [this list](https://cylc.github.io/cylc-doc/stable/html/user-guide/writing-workflows/runtime.html#task-event-template-variables)

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [ ] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

2023-12-14 15:19 UTC, wxtim commented on cylc/flow/scripts/lint.py
> +    'workflow_url': 'workflow_URL from workflow metadata',
You can set these items in 

```
# flow.cylc
[meta]
    workflow_url = "www.hat.ever"

[runtime]
    [[task]]
        [[[meta]]]
            task_url = "some://url"

```
And they will be available.

2023-12-14 15:35 UTC, MetRonnie approved these changes

2023-12-14 16:27 UTC, wxtim commented on cylc/flow/scripts/lint.py
> +    'workflow_url': 'workflow_URL from workflow metadata',
I agree. I'll have a think about how this might work.

2023-12-14 17:19 UTC, wxtim commented on cylc/flow/scripts/lint.py
> +    'workflow_url': 'workflow_URL from workflow metadata',
@MetRonnie  - Have another look, I should think that it's better now.

2023-12-14 17:33 UTC, MetRonnie approved these changes

2023-12-14 17:34 UTC, MetRonnie requested changes
Ah wait, got test failures

2023-12-15 16:29 UTC, wxtim commented
> Ah wait, got test failures

Tests earning their keep. Hopefully Will pass now.

2023-12-15 17:11 UTC, MetRonnie approved these changes
:+1:

2023-12-20 09:52 UTC, markgrahamdawson approved these changes

2023-12-20 10:03 UTC, merged