Xtrig arg validate
cylc/cylc-flow pull request #5955
Opened 2024-02-01 14:09 UTC by wxtim

Close #5448 

Replaces https://github.com/cylc/cylc-flow/pull/5452, to which I have added tests.

From @hjoliver 
> This is not just a bug-fix for the `wall_clock` xtrigger - I've gone for a generic approach: - if an xtrigger module has a function called `validate_config` it will be called at validation time, with the parsed args.

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [ ] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

2024-02-01 15:56 UTC, wxtim commented
@markgrahamdawson  requesting a second review because this is quite collab between Hilary and I at this point.

2024-02-01 17:45 UTC, MetRonnie requested changes
I realised it's trivially simple to automatically ensure xtrigger function args match the function signature at validation time

PR open here: https://github.com/wxtim/cylc/pull/59

2024-02-02 08:24 UTC, wxtim commented on cylc/flow/xtriggers/wall_clock.py
> +    except (ValueError, AttributeError):
I realized upon testing that we probably wanted to handle `f_kwargs["offset"]` not being a string. TBH, I'm not sure that it wouldn't be a case where `except Exception` would be justified - 99% of errors here are going to be user error, and for the 1% there's debug mode.

2024-02-02 10:50 UTC, MetRonnie commented on cylc/flow/xtriggers/wall_clock.py
> +    except (ValueError, AttributeError):
I'm not sure how `AttributeError` woild be raised, but you make a fair argument

2024-02-05 11:16 UTC, MetRonnie approved these changes

2024-02-05 12:22 UTC, MetRonnie commented on cylc/flow/xtriggers/xrandom.py
> +    # convert to kwarg
```suggestion
    The rules for args are:
    * percent: Must be 0 ≤ x ≤ 100
    * secs: Must be an integer.
    """
    # convert to kwarg for clarity
```

2024-02-05 15:47 UTC, MetRonnie commented
Flake8

2024-02-05 15:47 UTC, MetRonnie commented
Woops, wrong button. Re-open when flake8 addressed

2024-02-06 16:29 UTC, wxtim commented
> Woops, wrong button. Re-open when flake8 addressed

Fixed locally. Reopened so CI runs. Hopefully works on CI too.

2024-02-06 16:44 UTC, MetRonnie approved these changes

2024-02-15 18:46 UTC, MetRonnie commented
I'm looking at the failing tests

2024-02-16 16:32 UTC, MetRonnie requested changes
While looking at the test failures, I realised the implementation of `xrandom`'s `validate` function was flawed with respect whether you used args vs kwargs.

Then I realised I could simplify the way validation is carried out, PR open at https://github.com/wxtim/cylc/pull/60

2024-02-20 11:35 UTC, MetRonnie commented
Kicking tests

2024-02-20 11:37 UTC, MetRonnie commented
Ah right, @wxtim when you squash merge a PR make sure you remove `[skip ci]` from the commit description otherwise the tests will not run

2024-02-20 11:37 UTC, MetRonnie approved these changes

2024-02-21 16:18 UTC, MetRonnie commented
@wxtim Any objections if I merge this? I think enough due process has occurred at this point

2024-02-22 08:17 UTC, merged

2024-02-22 08:18 UTC, wxtim commented
> Ah right, @wxtim when you squash merge a PR make sure you remove `[skip ci]` from the commit description otherwise the tests will not run

That seems reasonable - All the code has been reviewed by two pairs of eyes in effect even if the review was not linear.