Group trigger
cylc/cylc-flow pull request #6395
Opened 2024-10-06 23:41 UTC by hjoliver

Implement group trigger proposal: https://github.com/cylc/cylc-admin/pull/197

(Proposal not approved yet, but IMO it's a clear winner, and I wanted to code it up while still fresh in the brain). 

Current master, on triggering one or more tasks: run them all immediately regardless of prerequisites.

This branch, on triggering one or more tasks: satisfy any off-group (aka off-flow) prerequisites

Result: we can trigger a sub-graph "naturally" by specifying all of its tasks (via family name or not):
- tasks with only off-group prerequisites will trigger immediately
- the flow will respect in-group prerequisites
- no stall due to unsatisfied off-group prerequisites

(Making a draft PR out of it now, to help sort out the test battery impact).

**Check List**

- [ ] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [ ] Contains logically grouped changes (else tidy your branch by rebase).
- [ ] Does not contain off-topic changes (use other PRs for other changes).
- [ ] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [ ] Tests are included (or explain why tests are not needed).
- [ ] Changelog entry included if this is a change that can affect users
- [ ] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [ ] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

2024-10-07 04:41 UTC, hjoliver commented
The test battery passes, so this does not break existing `trigger` and `set` functionality :tada: I just need to get some more coverage of the new code.

2024-12-19 11:39 UTC, hjoliver commented
(Updated after major changes on master)

2024-12-20 01:31 UTC, hjoliver commented
Note on changes to reference logs: group trigger causes triggering by satisfying prerequisites, rather than by direct triggering despite unsatisfied prerequisites ... so triggering now gets logged as (e.g.) `1/b triggered off ['1/a']` instead of `1/b triggered off [ ]`.

2025-01-10 00:31 UTC, hjoliver commented
(All tests were passing until my latest change to incorporate the new `cylc remove` stuff ... TBD)

2025-02-27 11:08 UTC, hjoliver commented
(Updated from master and deconflicted)

2025-03-14 00:18 UTC, hjoliver commented
(rebased and deconflicted)

2025-03-24 00:30 UTC, hjoliver commented
(Now that the proposal has been reviewed, I've converted this back to Draft so we can check on proposal compliance once all the details are agreed).

2025-03-28 04:28 UTC, hjoliver commented
(Proposal example works, test battery all good - I should be able to unDraft this early next week).

2025-03-28 05:49 UTC, hjoliver commented on cylc/flow/scheduler.py
> +                    LOG.error(f"[{itask}] ignoring trigger - already active")
TODO: still need to merge the flow on these guys

2025-04-07 08:32 UTC, hjoliver commented
(Updated from master and deconflicted (ouch) to pick up #6691 )

2025-04-08 10:47 UTC, oliver-sanders commented
Happy that only the group start-tasks will run. Don't see any real need to work around this.

2025-05-09 03:58 UTC, hjoliver commented
Integrated xtrigger prerequisite setting. Tested with this:
```cylc
[scheduling]
    [[xtriggers]]
        xoff = xrandom(0)  # never
    [[graph]]
        R1 = """
            failer? => GROUP => cleanup
            failer:fail? => triggerer
            off => c  # off-group task prerequisite
            @xoff => b  # off-group xtrigger prerequisite
             a => b & c  # GROUP internal triggers
        """
[runtime]
    [[failer, off]]
        script = false
    [[GROUP]]
    [[a, b, c]]
        inherit = GROUP
    [[triggerer]]
        script = "cylc trigger $CYLC_WORKFLOW_ID //1/a //1/b //1/c"
    [[cleanup]]
        script = "cylc remove $CYLC_WORKFLOW_ID//1/*:failed"
```

2025-05-13 04:20 UTC, hjoliver commented
TODO:
- [x] code tidied and TODOs addressed
- [ ] test for xtrigger prequisite satisfaction in a group trigger operation
- [ ] replace `tests/f/cylc-trigger/08-group-trigger` with integration tests

2025-05-14 01:24 UTC, hjoliver commented
Done.

2025-05-15 08:54 UTC, wxtim commented
Looks like something is going consistently wrong with 3.7?

2025-05-15 09:00 UTC, hjoliver commented
All tests passed on rerun today - maybe you just need to reload your browser to show up to date results?

2025-05-27 09:52 UTC, oliver-sanders commented on cylc/flow/scheduler.py
> +                    LOG.error(f"[{itask}] ignoring trigger - already active")
We are likely to hit this message a lot with group trigger. Maybe demote to warning (?) and batch up the messages rather than issuing one per task.

2025-05-27 09:55 UTC, oliver-sanders commented on cylc/flow/scheduler.py
> +        )
We do a lot of `entry in group_ids` comparisons below. Convert to a set for O(1) performance:

```suggestion
        group_ids = {
            *((tdef.name, str(point)) for (tdef, point) in inactive),
            *((itask.tdef.name, str(itask.point)) for itask in active),
        }
```

2025-05-27 10:15 UTC, oliver-sanders commented on cylc/flow/scheduler.py
> +        for tdef, point in stuff:
```suggestion
        for tdef, point in {*inactive, *active_tasks_to_remove):
```

2025-05-27 10:20 UTC, oliver-sanders commented on cylc/flow/scheduler.py
> +                )
Write as a generator, otherwise, the entire set will be built before the `any` is allowed to return (even if the first item is `True`).

```suggestion
                in_flow_prereqs = any(
                    key
                    for pre in tdef.get_prereqs(point)
                    for key in pre.keys()
                    if (key.task, str(key.point)) in group_ids
                )
```

2025-05-27 10:24 UTC, oliver-sanders commented on cylc/flow/task_pool.py
>              return None
I think this is leftover from before the remove proposal? Remove now strips the specified flow numbers so I don't think this is valid any more.

2025-05-27 11:46 UTC, oliver-sanders commented on cylc/flow/task_pool.py
> +            flow_nums = self.get_flow_nums(flow or [FLOW_ALL], flow_descr)
Isn't the `FLOW_ALL` default handled upstream of this code?

```suggestion
            flow_nums = self.get_flow_nums(flow, flow_descr)
```

2025-05-27 11:51 UTC, oliver-sanders commented on cylc/flow/task_proxy.py
> +        return self.identity == other.identity
`self.transient`, `self.reload_successor`?

2025-05-27 11:55 UTC, oliver-sanders commented on cylc/flow/task_proxy.py
> +        return hash(self.identity)
What about reload-successors or transient task proxy objects?

I think these `__eq__` and`__hash__` methods might be a bit dubious, however, it looks like the code works fine without them, so maybe we can just drop them? Note, Python classes get these methods by default, objects only compare equal to themselves which is all we need and wouldn't cause issues in edge cases.

2025-05-27 12:03 UTC, oliver-sanders commented on tests/unit/scripts/test_cylc.py
> +        del os.environ["CYLC_PYTHONPATH"]
Use `monkeypatch.delenv`

2025-06-16 09:26 UTC, oliver-sanders commented on cylc/flow/scheduler.py
> +    ):
Co-locate this with the other commands in `cylc.flow.commands`.

2025-06-16 12:35 UTC, wxtim commented on cylc/flow/scripts/trigger.py
> +  $ cylc trigger 'test//*:failed'  # (quotes required)
IMO this is important distinction.

```suggestion
  $ cylc trigger 'test//*:failed'  # (single-quotes required)
```

2025-06-16 13:30 UTC, wxtim commented on tests/integration/test_force_trigger.py
> +                'xr': 'xrandom(0)'  # never satisfied
Closer to self documenting?
```suggestion
                'xtrigger': 'echo("No", False)'
```

2025-06-16 13:35 UTC, wxtim commented on tests/integration/test_force_trigger.py
> +                    x => a => b & c => d => e => y
```suggestion
                    x => a
                    # Sub-graph for group trigger
                    a => b & c => d
                    # Later tasks
                    d => e => y
```

2025-06-16 13:37 UTC, wxtim commented on tests/integration/test_force_trigger.py
> +                    @xr => off => b  # off-group task prerequisite
Why does `off` need a dependence on the xtrigger? How is this different from x?

2025-06-16 15:37 UTC, oliver-sanders commented
Added a test to cover details point (4) from the proposal with an awkward example (test passes) - https://github.com/hjoliver/cylc-flow/pull/66

Started working on a test to cover `--flow` interaction but hit the above problem. Here's the test template I was working on:

```python
async def test_trigger_group_in_flow(flow, scheduler, run, complete, log_filter, reflog):
    id_ = flow({
        'scheduling': {
            'graph': {
                'R1': 'a => b => c => d'
            }
        }
    })
    schd = scheduler(id_, paused_start=False)
    async with run(schd):
        await run_cmd(hold(schd, ['1/d']))

        triggers = reflog(schd)
        await complete(schd, '1/a')
        await run_cmd(force_trigger_tasks(schd, ['1/b'], ['2']))
        await complete(schd, '1/c')
        assert triggers == {
            ('1/a', None),
            ('1/b', ('1/a',)),
            ('1/c', ('1/b',)),
        }

        # state is now:
        # * a - succeeded flow=1
        # * b - succeeded flow=1,2
        # * c - succedded flow=1,2
        # * d - waiting (held)

        triggers = reflog(schd)
        await run_cmd(force_trigger_tasks(schd, ['1/a', '1/b', '1/c'], ['2']))
        await complete(schd, '1/c', timeout=10)
        assert triggers == {
            ('1/a', None),
            ('1/b', ('1/a',)),
            ('1/c', ('1/b',)),
        }
```

2025-06-16 15:39 UTC, oliver-sanders commented on tests/integration/test_force_trigger.py
> +                    @xr => off => b  # off-group task prerequisite
I think the point here is:

* In-group xtriggers should be satisfied by the trigger (just as they would have been if we had triggered the tasks one-by-one).
* However, this should not affect off-group tasks (i.e. satisfying `@xr` for `x` should not also satisfy it for the off-group task `x`).

2025-06-16 15:40 UTC, oliver-sanders commented on cylc/flow/scripts/trigger.py
> +  $ cylc trigger 'test//*:failed'  # (quotes required)
Not true:

```console
$ echo "*"  # double quotes
*
$ echo '*'  # single quotess
*
$ echo *  # no quotes
changes.d CHANGES.md conda-environment.yml ...
```

2025-06-17 05:16 UTC, hjoliver commented
Thanks for starting on this @oliver-sanders  - once again, I'll get back on it ASAP. I'm still stuck in local project admin stuff at the FY-end boundary, plus TAG meeting on Thursday ... but I should be done with all that soon...

2025-06-17 06:09 UTC, hjoliver commented
(bug confirmed with a real workflow ... I initially though not, but had borked my environment)

2025-06-18 01:11 UTC, hjoliver commented
OK fixed - the bug was a small regression (I had definitely tested this kind of scenario). I had accidentally swapped out int flow_nums for the str version in one place, and a single missed type annotation let it through 😬 

```diff
diff --git a/cylc/flow/scheduler.py b/cylc/flow/scheduler.py
index 37d0aa2e1..4fdeb7b02 100644
--- a/cylc/flow/scheduler.py
+++ b/cylc/flow/scheduler.py
@@ -1121,7 +1121,7 @@ class Scheduler:
         if active or inactive:
             self.remove_matched_tasks(active, inactive, flow_nums)

-    def remove_matched_tasks(self, active, inactive, flow_nums):
+    def remove_matched_tasks(self, active, inactive, flow_nums: 'FlowNums'):
         # Mapping of *relative* task IDs to removed flow numbers:
         removed: Dict[Tokens, FlowNums] = {}
         not_removed: Set[Tokens] = set()
@@ -1317,7 +1317,7 @@ class Scheduler:
                 active_tasks_to_remove.append(itask)

         # remove all inactive and selected active group members
-        self.remove_matched_tasks(active_tasks_to_remove, inactive, flow)
+        self.remove_matched_tasks(active_tasks_to_remove, inactive, flow_nums)

         # store removal results before moving on
         self.workflow_db_mgr.process_queued_ops()
```

2025-06-18 02:37 UTC, hjoliver commented on cylc/flow/scheduler.py
> +                    LOG.error(f"[{itask}] ignoring trigger - already active")
Done.

2025-06-18 02:49 UTC, hjoliver commented on cylc/flow/scheduler.py
> +        for tdef, point in stuff:
Doesn't work because `active_tasks_to_remove` holds task proxies, not `(tdef, point)`.

(Changed the silly variable name though).

2025-06-18 02:54 UTC, hjoliver commented on cylc/flow/scheduler.py
> +                )
Done.

2025-06-18 03:27 UTC, hjoliver commented on cylc/flow/task_pool.py
>              return None
Requires some thought, and not really in scope here.

 I think this code avoids automatic respawning of tasks removed by a suicide trigger:

https://github.com/cylc/cylc-flow/pull/6186#discussion_r1669727292

https://github.com/cylc/cylc-flow/issues/6066

2025-06-18 03:38 UTC, hjoliver commented on cylc/flow/task_pool.py
> +            flow_nums = self.get_flow_nums(flow or [FLOW_ALL], flow_descr)
At this point, no - I just checked. I might be worth going over flow-num handling and defaulting generally in case it could be streamlined, but maybe not on this PR.

2025-06-18 03:39 UTC, hjoliver commented on cylc/flow/task_proxy.py
> +        return self.identity == other.identity
Ah, not sure what your point is?

2025-06-18 03:40 UTC, hjoliver commented on cylc/flow/task_proxy.py
> +        return self.identity == other.identity
Ok, you've explained in the next comment below.

2025-06-18 03:42 UTC, hjoliver commented on cylc/flow/task_proxy.py
> +        return hash(self.identity)
I'm reasonably sure I would have added this code for a good reason - but I'll have to try to remind myself, too long ago...

2025-06-18 04:12 UTC, hjoliver commented on cylc/flow/scheduler.py
> +    ):
It is!  It's just under `def remove_tasks` - although then I split a block of common code out of that method, but left it in-place to make for a minimal code change - is it the positioning of that that you're complaining about?.

2025-06-18 04:17 UTC, hjoliver commented on tests/integration/test_force_trigger.py
> +                'xr': 'xrandom(0)'  # never satisfied
I kinda forgot about the toy `echo` xtrigger, but my comment is fine for self-doc isn't it?  The important thing is, it's an xtrigger that will never be naturally satisfied.

2025-06-18 04:28 UTC, hjoliver commented
> Started working on a test to cover --flow interaction but hit the above problem. Here's the test template I was working on:

I added your test @oliver-sanders - it passes.

2025-06-18 06:27 UTC, hjoliver commented
Huh, the one-liner bug fix has caused several functional test fails by changing how flow=none tasks end up in the DB. (Tested with `flow-triggers/13-noflow-nomerge` at least).

I've verified that claim by backing out just the fix. 

I'll have to investigate tomorrow.

2025-06-18 08:44 UTC, oliver-sanders commented on cylc/flow/scheduler.py
> +    ):
> It is! 

???

This code has been yanked out into the Scheduler class for some reason, it should be co-located with the other commands in `cylc.flow.commands`.

2025-06-18 08:49 UTC, wxtim commented on tests/integration/test_force_trigger.py
> +                'xr': 'xrandom(0)'  # never satisfied
Yes - whatever - shouldn't block review.

2025-06-18 10:01 UTC, oliver-sanders commented on cylc/flow/task_proxy.py
> +        return hash(self.identity)
The code seems to work fine with them removed, all unit/integration tests pass.

I can't think of cases where this sort of comparison would be useful. By default an object is only equal to itself which seems like a sensible test for us where `TaskProxy` objects are intended to be unique (besides proxy reload successors and transient objects).

```python
class Foo():

    def __init__(self, x):
        self.x = x


class Bar(Foo):

    def __eq__(self, other):
        return self.x == other.x

    def __hash__(self):
        return hash(self.x)

assert Foo(1) != Foo(1)  # is not the same object
assert Bar(1) == Bar(1)  # obj.x is the same
```

2025-06-18 10:02 UTC, oliver-sanders commented on tests/integration/test_force_trigger.py
> +                'xr': 'xrandom(0)'  # never satisfied
I think `# never satisfied` is clear enough. Call the xtrigger `@fail` for serious clarity!

2025-06-18 10:35 UTC, hjoliver commented on cylc/flow/scheduler.py
> +    ):
Oh, I see what you mean.  

It was yanked out of the task_pool module, not commands - just as @MetRonnie did to the remove command.

Both trigger and remove have a small wrapper in commands.  I think I was just following Ronnies example, since the two commands have relevant similarities.

2025-06-18 10:37 UTC, hjoliver commented on tests/integration/test_force_trigger.py
> +                'xr': 'xrandom(0)'  # never satisfied
I considered that, but technically xtriggers don't fail, they either "succeeded" or "not succeeded yet". I suppose `@never` might be the serious-clarity option!

2025-06-18 10:52 UTC, oliver-sanders commented
More tests: https://github.com/hjoliver/cylc-flow/pull/67

2025-06-18 11:10 UTC, MetRonnie commented on cylc/flow/scheduler.py
> +    ):
I didn't remove anything from `commands.py` in #6472, just moved it from `task_pool.py` to `scheduler.py` as it needed to call the scheduler's `kill_tasks` method. It looks like you've done a similar thing and need to call the scheduler's `remove_matched_tasks` method

2025-06-18 11:27 UTC, oliver-sanders commented on cylc/flow/scheduler.py
> +            # TODO: is the enclosing 'if' statement correct here?
TODO

2025-06-18 11:27 UTC, hjoliver commented
I showed the one-liner above: https://github.com/cylc/cylc-flow/pull/6395#issuecomment-2982284844 

(Actually it was a two-liner, but one line was just a missing type annotation).

2025-06-18 11:28 UTC, hjoliver commented on cylc/flow/scheduler.py
> +            # TODO: is the enclosing 'if' statement correct here?
Yes, I just put that there minutes ago. It fixes the problem, but I want to come back tomorrow and make really sure that it's the right thing to do there.

2025-06-18 11:29 UTC, hjoliver commented on cylc/flow/scheduler.py
> +    ):
Correct!

2025-06-18 11:43 UTC, hjoliver commented on cylc/flow/scheduler.py
> +            # TODO: is the enclosing 'if' statement correct here?
(The one-liner you asked about changed `flow` (`[str]`) to `flow_nums` (`[int]`) in line 1333 above; I understand why it broke the tests now, despite definitely being a bug fix).

2025-06-18 11:45 UTC, hjoliver commented
All test passing now, including the ones just merged from you @oliver-sanders 🎉   Nearly there...

2025-06-19 01:26 UTC, hjoliver commented
Regarding the new TODO (above) - the DB remove code seems to behave slightly differently to what I expected for the trigger command ... I'll post the question on Element to avoid cluttering the PR more.

2025-06-19 02:18 UTC, hjoliver commented
The TODO discussion:  see my Element post re expected default behaviour of remove vs trigger.

2025-06-19 12:20 UTC, oliver-sanders commented
> The TODO discussion: see my Element post re expected default behaviour of remove vs trigger.

Commented there. The status quo makes sense to me, can't think why we would want to change it. Out of scope either way.

2025-06-24 07:01 UTC, hjoliver commented
Agreed - out of scope. I just raised it here because I was surprised (my bad) that remove had different default-flow semantics than trigger, when I ran into it on this branch, and thought I'd better confirm that no one expected remove-via-trigger to behave the same as standalone remove in that respect.

2025-06-25 14:12 UTC, oliver-sanders commented on cylc/flow/scheduler.py
> +    ):
Er, that doesn't actually make sense in either case.

The commands are provided with `schd` as the first argument. This is exactly the same as the `self` argument! The code does not need to be moved into the Scheduler to call scheduler methods.

2025-06-26 11:16 UTC, MetRonnie commented on cylc/flow/scheduler.py
> +    ):
No code was ever moved out of `commands.py`; only out of `task_pool.py`. Yes in principle we could move it into `commands.py`.

2025-06-26 22:38 UTC, hjoliver commented on cylc/flow/scheduler.py
> +    ):
What he said. 

Like for remove, trigger was moved out of task_pool to scheduler. It was never in commands.

In both cases, there was just a small wrapper in commands that called the task pool (now scheduler) methods.

2025-06-27 01:25 UTC, hjoliver commented
OK, I've handled the different default-flow semantics between `trigger` and `remove` (as discussed in Element chat) and removed the one test that this breaks. 

All other tests pass 🎉

Posted an issue for the removed case: https://github.com/cylc/cylc-flow/issues/6819

2025-06-27 09:25 UTC, oliver-sanders commented on cylc/flow/task_pool.py
> +        force: bool = False
What does `force` do?

A comment or some docstring would be good.

2025-06-27 09:25 UTC, oliver-sanders commented on cylc/flow/scheduler.py
> +                    self.remove_matched_tasks(empty_a, inactive, flow_nums)
I thought this was right before, I'm not sure I understand this change?

Before, if `--flow=all`, then `flow_nums` is already set to all active flows:

```python
flow_nums = self.pool.get_flow_nums(flow, flow_descr)
```

But now, `flow_nums` is still all active flows, but we remove active tasks (from `flow_nums`), then we recompute the `flow_nums`:

```python
self.pool.get_flow_nums([FLOW_ALL])
```

Which may now differ from `flow_nums` because we haven't spawned the new task(s) yet?

2025-06-27 11:56 UTC, oliver-sanders commented on cylc/flow/scheduler.py
> +                    self.remove_matched_tasks(empty_a, inactive, flow_nums)
To flesh out the edge case, I had a go at extending a test to cover triggering tasks with the `--flow=all` default WHEN the tasks previously ran in a flow that is no longer active:

```diff
--- a/tests/integration/test_force_trigger.py
+++ b/tests/integration/test_force_trigger.py
@@ -17,20 +17,24 @@
 import logging
 from typing import (
     Any as Fixture,
-    Callable
+    Callable,
 )
 
 import pytest
 
+from cylc.flow import LOG
 from cylc.flow.commands import (
     force_trigger_tasks,
-    reload_workflow,
     hold,
+    reload_workflow,
     resume,
     run_cmd,
     set_prereqs_and_outputs,
+    stop,
 )
 from cylc.flow.cycling.integer import IntegerPoint
+from cylc.flow.flow_mgr import FLOW_ALL
+from cylc.flow.workflow_status import StopMode
 
 
 async def test_trigger_workflow_paused(
@@ -485,3 +489,41 @@ async def test_trigger_group_in_flow(
             ('b', '[2]'),
             ('c', '[2]'),
         }
+
+        # breakpoint()
+        # assert schd.pool._get_active_flow_nums() == {'2'}
+        await run_cmd(stop(schd, mode=StopMode.REQUEST_CLEAN, flow_num=1))
+
+        assert schd.pool._get_active_flow_nums() == {2}
+
+        assert [
+            (itask.identity, itask.flow_nums)
+            for itask in schd.pool.get_tasks()
+        ] == [('1/d', {2})]
+
+        LOG.critical('AAAA')  # look for this in the log pytest shows if the test fails
+        await run_cmd(force_trigger_tasks(schd, ['1/a', '1/b', '1/c', '1/d'], [FLOW_ALL]))
+
+        assert set(db_select(
+            schd,
+            True,
+            'task_outputs',
+            'name',
+            'flow_nums',
+        )) == {
+            # original run
+            ('a', '[1]'),
+            ('b', '[1]'),  # flow "2" has been removed
+            ('c', '[1]'),  # flow "2" has been removed
+            ('d', '[1]'),
+
+            # subsequent run
+            ('a', '[]'),
+            ('b', '[]'),
+            ('c', '[]'),
+
+            ('a', '[2]'),
+            ('b', '[2]'),
+            ('c', '[2]'),
+            ('d', '[2]'),
+        }
```

* Use `cylc stop --flow` to stop flow `1`. The only active flow is now `2`.
* Trigger a group of tasks which ran in flows `[1]`, `[1, 2]` and `[2]` to see how the operation handles each.
* Cylc logs that it is triggering/removing the appropriate tasks (in two batches, one for active and one for inactive tasks) - makes sense.
* But strangely, the `flow=2` entries remain in the DB afterwards?

2025-06-28 00:04 UTC, hjoliver commented on cylc/flow/scheduler.py
> +                    self.remove_matched_tasks(empty_a, inactive, flow_nums)
> I thought this was right before, I'm not sure I understand this change? 

I'll double check this soon, but I think what you've missed is flow_nums can be *empty*.  For trigger that means "all active" flows, but for remove that means "all" flows. That's why I'm recomputing them with an explict FLOW_ALL on calling the remove method.

2025-06-30 04:57 UTC, hjoliver commented on cylc/flow/scheduler.py
> +                    self.remove_matched_tasks(empty_a, inactive, flow_nums)
(I've spent all on day #6813  and #6821 - back to this tomorrow).

2025-06-30 10:39 UTC, oliver-sanders commented on cylc/flow/scheduler.py
> +                    self.remove_matched_tasks(empty_a, inactive, flow_nums)
> but I think what you've missed is flow_nums can be empty.

If that's the case, then the earlier evaluation of `flow_nums = self.pool.get_flow_nums(flow, flow_descr)` at line 1263 would suffer from the same problem:

https://github.com/cylc/cylc-flow/pull/6395/files#diff-90711b005fe27b9f894e6cd09f08816d847dcf853518894c6b7e2139784cbcb8R1263

Either way, I don't think we should be recomputing the flow numbers post-remove?

2025-06-30 10:45 UTC, oliver-sanders commented on cylc/flow/scheduler.py
> +    ):
> In both cases, there was just a small wrapper in commands that called the task pool (now scheduler) methods - and git blame fingers you @oliver-sanders for the wrappers - so presumably you made the decision to do it that way??

At the time, remove and trigger were implemented in the task pool, so I left them there. This arrangement dates back a long way (Cylc 6 or earlier) and makes reasonable sense since these are operations on the task pool itself.

Now these implementations have been pulled out into the scheduler class which is mostly about application control flow and event loop. The scheduler class is pretty unwieldy, so I've made some small efforts to move logic out of it into more self-contained modules, e.g, the main-loop plugins allowed us to pull out the health check, auto-restart and bad hosts logic; and the commands module allowed us to pull out the command implementations. Little by little...

> If not, happy to move the lot into commands.py ...

Er, yes please.

2025-07-02 05:48 UTC, hjoliver commented
Somewhat out-of-scope IMO (given the approved history of the similar `remove` function) but the last rather chunky commit moves trigger and remove out of scheduler and into commands as requested, which had some annoying implications in the tests.

2025-07-02 05:48 UTC, hjoliver commented on cylc/flow/scheduler.py
> +            # TODO: is the enclosing 'if' statement correct here?
(This comment is out of date, the replacement code block is still under review).

2025-07-02 05:49 UTC, hjoliver commented on cylc/flow/scheduler.py
> +    ):
Done.

2025-07-02 22:06 UTC, hjoliver commented on cylc/flow/scheduler.py
> +                    self.remove_matched_tasks(empty_a, inactive, flow_nums)
OK I finally got back to this. 

Sorry, my bad - I think I missed your main point because I didn't notice that I'd stupidly moved the `get_flow_nums` call into the remove call arg list to avoid a temporary variable ... by jumping over the earlier remove call that could change the task pool.

I'll try to clean up flow-nums handling a bit. It's gotten quite confusing as now have three commands (set, trigger, remove) that each handle the same CLI options slightly differently.

2025-07-03 02:58 UTC, hjoliver commented on cylc/flow/scheduler.py
> +                    self.remove_matched_tasks(empty_a, inactive, flow_nums)
I've tried to clean up flow-nums handling, but not pushed the result up yet as I need to adjust a bunch of tests first. I'll do that tomorrow...

2025-07-03 03:00 UTC, hjoliver commented on cylc/flow/task_pool.py
>              return None
See #6813 and #6835

2025-07-08 06:37 UTC, hjoliver commented
Converted briefly back to draft till I've finished the final tweaks (in progress).

2025-07-09 02:48 UTC, hjoliver commented on cylc/flow/scheduler.py
> +                    self.remove_matched_tasks(empty_a, inactive, flow_nums)
I'm resolving this discussion, after significantly refactoring flow-number handling to allow (among other things) simplifying the remove-via-trigger bit. (We can discuss the new code if you want to query anything there).

2025-07-09 03:42 UTC, hjoliver commented on cylc/flow/task_pool.py
> +        force: bool = False
Removed. It was an attempt at handling the long-standing TODO problem that we eventually spun off to https://github.com/cylc/cylc-flow/issues/6813 (and fixed by https://github.com/cylc/cylc-flow/pull/6835)

2025-07-09 04:08 UTC, hjoliver commented on cylc/flow/task_proxy.py
> +        return hash(self.identity)
``` 
        # (Needed e.g. for adding to task_pool.tasks_to_trigger sets)
```
This comment suggests to me that I must have ran into trouble with multiple instances of the same task proxy being added to the "tasks_to_triggers" sets. 

However, testing just now, I can't make that happen, so maybe it was due to something upstream that I fixed already (e.g. maybe a transient task proxy was being used unnecessarily somewhere, for an active task, rather than grabbing the same (active) object).

So ... I've removed the methods. Hopefully that won't come back to haunt us.

2025-07-09 04:29 UTC, hjoliver commented
All comments addressed, I think.

-----

I simplified flow-number handling quite a bit, so that defaulting to "all active flows" (in set and trigger) can now be done in one place, and the associated remove (in trigger) can be done in one go.

I also simplified some IMO unnecessary complexity, some of which went beyond the proposals (some maybe crept in on this branch, but some on master):

 `remove` command
   - default means ALL flows
   -  `--flow=all` means ALL flows (same)
    
`set/trigger` inactive tasks
   - default means ALL ACTIVE flows
   -  `--flow=all` means ALL ACTIVE flows (same)
 
`set/trigger` active tasks
   - default means ONLY EXISTING (already assigned) flows
   - `--flow=all` means merge EXISTING and ALL ACTIVE flows (NOT same)

To clean this up,  **I entirely ditched the `--flow=all` option** and made **the same default for inactive and active tasks.** (

Rationale (in addition to the confusingly inconsistent set of `--flow=all` meanings above):
- it is pointless to have a specific option that is identical to the default, if it is not naturally required e.g. as a member of a sequence (n-window extent can be 0,1,2,3 with default 1 - that's fine)
-  and the one case where it differed from the default (set/trigger active tasks) was arguably wrong, to the extent that it matters at all, in the context of group trigger (there will almost always be inactive tasks in the group, which necessarily get all active flows anyway, so why not do it for active tasks as well?).

----

So now, much simpler:

-  `remove` command: default means ALL flows
- `set/trigger` commands: default means ALL ACTIVE flows (which includes EXISTING if any)
- (and no need for a `--flow=all` option anywhere)
 
(I don't think this has any unpleasant practical consequences, and it won't affect most users at all, especially after this PR makes use of multiple concurrent flows largely unnecessary).

2025-07-10 13:30 UTC, oliver-sanders commented on cylc/flow/task_pool.py
> -            taskdef.name, point, flow_nums, flow_wait=flow_wait, force=True
This option was being used. Was this a bug?

2025-07-11 09:57 UTC, oliver-sanders commented
> I entirely ditched the --flow=all option and made the same default for inactive and active tasks

This needs to be carefully tested for inter-version compatibility. I found one breakage in forward compatibility for the "remove" command in the GUI as the flow argument defaults to all in the GraphQL schema.

The breakage should be easy to fix with a compat shim, but if it takes while maybe bump this part to another PR?

2025-07-11 15:33 UTC, oliver-sanders commented on changes.d/6395.feat.md
> +and leave in-group prerequisites to be satisfied by the flow.
Great technical description, but it's not obvious what this means to users:

```suggestion
`cylc trigger` now respects the dependencies between tasks allowing it to be used to (re)-run a subgraph of tasks.
```

2025-07-11 15:33 UTC, oliver-sanders commented on cylc/flow/flow_mgr.py
> +             'By default, assign to all active flows; otherwise'
```suggestion
             ' By default, assign to all active flows; otherwise'
```

2025-07-14 00:09 UTC, hjoliver commented on changes.d/6395.feat.md
> +and leave in-group prerequisites to be satisfied by the flow.
I'm not that happy about dumbing down explanations for the least savvy users, 

The trouble with not mentioning flow erasure and off-group prerequisites is that more savvy users users (and there are at least a few of them) are likely to assume that (or at least wonder if) trigger won't achieve the desired result without manually handling those aspects.

I'll take the simplified description, and add a short "advanced" description at the bottom.

2025-07-15 08:19 UTC, oliver-sanders commented on changes.d/6395.feat.md
> +and leave in-group prerequisites to be satisfied by the flow.
Changelog entries are intended to give a quick user-facing overview. Use the user guide to document the fine details.

> and there are at least a few of them

FYI, we don't have *any*.

2025-07-15 08:53 UTC, wxtim commented on changes.d/6395.feat.md
> +and leave in-group prerequisites to be satisfied by the flow.
> I'll take the simplified description, and add a short "advanced" description at the bottom.

Was going to suggest this.

2025-07-15 09:14 UTC, hjoliver commented on changes.d/6395.feat.md
> +and leave in-group prerequisites to be satisfied by the flow.
Sorry, my bad 🤦too much multi-tasking brain fry - from a quick look here (not via Files Changed) for some reason I assumed you were commenting on text at the top of the CLI help, not the change log (hence my response that I'd add an "advanced" section below it, which is clearly not gonna work for the change log). So, actually, I agree that my text is overkill for the change log.

> FYI, we don't have any.

Jeez, there must be some. Even if not, there *could* be (or *should* be) so we should still explain things well enough for users to understand what's going on if they do want or need to know (but yeah, not in the change log!).

2025-07-15 09:29 UTC, oliver-sanders commented on changes.d/6395.feat.md
> +and leave in-group prerequisites to be satisfied by the flow.
> Jeez, there must be some. 

A topic for another day, but, I have good reason/evidence for saying this. Our users are just abandoning their workflow runs rather than using new flows.

And, yeah, obvs no issue with that detail in the `cylc trigger --help`.

2025-07-15 09:46 UTC, oliver-sanders requested changes
Still reviewing (sorry, struggling for time ATM). The `--flow=all` change has introduced an inter-version compatibility bug which needs to be fixed - https://github.com/cylc/cylc-flow/pull/6395#issuecomment-3061595557 (if we bump the `--flow=all` change to another PR, this PR will be unstuck, otherwise it will have to be fixed here).

2025-07-15 15:13 UTC, wxtim commented on tests/integration/test_force_trigger.py
> +    """Only group start-tasks should run whilst the scheduler is paused.
Was this agreed? It feels like slightly odd behaviour - I'd expect that the entire subgraph would run if I'd deliberately triggered it whilst paused.

2025-07-15 15:13 UTC, wxtim commented on tests/integration/test_force_trigger.py
> +    The remaining tasks will run according to normal prerequsitie satisfaction
Spilling?
```suggestion
    The remaining tasks will run according to normal prerequisite satisfaction
```

2025-07-15 15:15 UTC, wxtim reviewed
.

2025-07-15 15:15 UTC, wxtim commented on tests/integration/test_force_trigger.py
> +    The remaining tasks will run according to normal prerequsitie satisfaction
Wonder whether it should be

```suggestion
    The remaining tasks will run as normal, when their prerequisites
    are satisfied.
```

2025-07-15 15:27 UTC, oliver-sanders commented on tests/integration/test_force_trigger.py
> +    """Only group start-tasks should run whilst the scheduler is paused.
It wasn't noticed/discussed in the proposal, but it was brought up above (https://github.com/cylc/cylc-flow/pull/6395#issuecomment-2782451295)

* At the moment, if you trigger a task whilst the workflow is paused, it will run.
* This is reasonable and there are use cases for doing so.
* With this change we allow trigger dependent tasks.
* You could use this to re-run an inter-dependent family or even the entire workflow.
* In order for workflow paused to mean something, we have to draw the line somewhere.
* We wouldn't want operators, not to be able to slam on the breaks when they need to.
* You can always push tasks through submission whilst the workflow is paused by triggering them again.

2025-07-15 21:50 UTC, hjoliver commented on changes.d/6395.feat.md
> +and leave in-group prerequisites to be satisfied by the flow.
Well I do have several here who have played around with new flows and commented on it being useful and powerful. But even if that weren't the case we still need to properly document how the system works. It is possible to start new flows, and there are good reasons to do it (group trigger is still using this feature under the hood too), and if someone tries it and needs to understand the behaviour they see then it should be documented (but not in the change log!).

2025-07-15 21:52 UTC, hjoliver commented on tests/integration/test_force_trigger.py
> +    The remaining tasks will run according to normal prerequsitie satisfaction
Damn, "prerequisite" has got to be the most mis-"spilled" word in the codebase. Other than "cylc". 🤣

2025-07-16 02:36 UTC, hjoliver commented on cylc/flow/task_pool.py
> -            taskdef.name, point, flow_nums, flow_wait=flow_wait, force=True
I presume you mean the `force` option, but I'm not sure where this diff came from. It's marked as outdated, and the code now shows no difference from master here (and no `force` option). Maybe the option got removed on master by another PR (and I've since rebased this branch). [... Nope, `git blame` says not].

2025-07-16 02:39 UTC, hjoliver commented
OK, last two commits:
- fixed a small off-topic remove bug that I ran noticed (highly unlikely that it affected anyone)
- shimmed `--flow=all` compat for old clients (tested with CLI and web UI, for set, trigger, remove)

2025-07-16 10:20 UTC, wxtim commented on tests/integration/test_force_trigger.py
> +    """Only group start-tasks should run whilst the scheduler is paused.
Sorry - I missed the comment.

2025-07-16 10:23 UTC, wxtim commented on tests/integration/scripts/test_back_compat_flow_all.py
> +    """blah"""
Remove or add helpful comment.

Why does this test back compatibility? As far as I can see it's only testing that providing a garbage flow number causes a failure?

2025-07-16 11:00 UTC, wxtim commented on tests/integration/test_force_trigger.py
> +        with pytest.raises(AssertionError):
This test feels isufficiently fragile - anything which causes a failure to complete task will cause this test to pass - if it's a total failure that's fine, but if it's a delay then the whole test could pass when it shouldn't.

2025-07-16 13:27 UTC, wxtim commented on tests/integration/test_force_trigger.py
> +            'graph': {
Worth covering the old ext-triggers whilst we're at it?
```suggestion
            'special tasks': {
                'external-trigger': 'ext_trigger("sent")'
            },
            'graph': {
```

2025-07-16 13:28 UTC, wxtim commented on tests/integration/test_force_trigger.py
> +                    @xr => x  # stop the flow starting
See https://github.com/cylc/cylc-flow/pull/6395/files#r2210436921
```suggestion
                    ext_trigger => x
                    @xr => x  # stop the flow starting
```

2025-07-16 13:37 UTC, wxtim commented on tests/integration/test_force_trigger.py
> +
And a check that ext-trigger has been seen

```suggestion
        assert log_filter(
            regex=(
                "1/a:waiting.* prerequisite force-satisfied: "
                "1/ext_trigger:succeeded"))

```

2025-07-16 13:41 UTC, wxtim commented on tests/integration/test_force_trigger.py
> +        # Create an active task that needs removing (to plug a coverage hole).
```suggestion
        # Create an active task that needs removing tp test that such a task is removed.
```

2025-07-16 14:25 UTC, wxtim commented
For general info, I tried this out merged with https://github.com/cylc/cylc-flow/pull/6852 and the GUI makes a lot of sense of the off-group dependencies.

2025-07-16 15:36 UTC, wxtim commented
### Bug

I would expect the following workflow to 
1. Start `a` and `b`. 
2. Run `trigger` which would
  2a. Leave `a` alone.
  2b. Kill `b`
  2c. Remove `b`
3. `b` would then retrigger, because `a:started` has occured.
4. `b:started` would retrigger `trigger`
5. infinite loop

However, at step 2 `b` is killed, but _not_ removed, and therefore cannot retrigger.

```cylc
[scheduling]
    cycling mode = integer
    [[graph]]
        R1 = a:started => b:started => trigger

[runtime]
    [[a, b]]
        script = sleep 3600

    [[trigger]]
        script = sleep 5; cylc trigger ${CYLC_WORKFLOW_ID} //1/a //1/b //1/trigger; sleep 10
```

2025-07-16 15:57 UTC, oliver-sanders commented
Confirmed. It looks like the implementation is trying to do the right thing (it kills `b`), but fails to actually remove it. Is it trying to remove the task from the wrong flow(s)?

2025-07-16 20:01 UTC, hjoliver commented on tests/integration/scripts/test_back_compat_flow_all.py
> +    """blah"""
Oops (newly added test, temporary "blah" not replaced).

> Why does this test back compatibility?

See my comment just above:
> shimmed `--flow=all` compat for old clients (tested with CLI and web UI, for set, trigger, remove)

The `--flow=all` option is no longer valid ("all" flows is now the default in all cases) but Oliver (rightly) asked me to support it as an incoming option from old (pre 8.5) clients.

> As far as I can see it's only testing that providing a garbage flow number causes a failure?

It tests that garbage flow numbers fail, but more importantly that a particular garbage flow number ("all") does not fail (as just described).  The new unit test in `commands.py` tests that it trasnslates to the default `flows = [ ]`).

2025-07-17 01:21 UTC, hjoliver commented
Actually, disconfirmed, with a caveat.

That's a kinda fiendish example @wxtim , as it turns out, but your expectations are a bit wrong. It should be this:

1.  Start `a` and `b` *and `trigger`*
2.   Run `trigger` which would
    2a. Leave `a` alone.
    2b. Kill `b` *and `trigger`*
    2c. Remove `b` *and `trigger`*
3. the workflow shuts down as completed when `a` succeeds, because `a:started` is a past event - the group start task is not going to complete any outputs, post intervention, to start the new flow.

This is likely not what the user intended, but it is what the proposal says.  The thing is, `b` will not retrigger because `a:started` is a past event.

Currently: user beware if triggering a group that contains active group start tasks (some outputs may already have spawned children).

2025-07-17 05:09 UTC, hjoliver commented on tests/integration/scripts/test_back_compat_flow_all.py
> +    """blah"""
Fixed the docstring.

2025-07-17 05:20 UTC, hjoliver commented on tests/integration/test_force_trigger.py
> +        with pytest.raises(AssertionError):
OK, I added an additional check for "waiting" status.

2025-07-17 05:57 UTC, hjoliver commented on tests/integration/test_force_trigger.py
> +            'graph': {
Yikes, good suggestion - I had entirely forgotten about old-style push external triggers. Luckily that's an easy fix... DONE

2025-07-17 06:13 UTC, hjoliver commented on tests/integration/test_force_trigger.py
> +                    @xr => x  # stop the flow starting
done

2025-07-17 06:33 UTC, hjoliver commented on tests/integration/test_force_trigger.py
> +
done

2025-07-17 08:20 UTC, wxtim commented
> But it IS a fiendish and revealing example, as it turns out.

I aim to please 😈

> put wrong task states in the datastore 😬 

This makes more sense:

<img width="148" height="110" alt="image" src="https://github.com/user-attachments/assets/67e812b3-fbdb-4ee4-bba9-152d8373a56b" />

> Actually, dis-confirmed as a bug! 
> However, it is likely not what the user intended... so PROPOSED PROPOSAL EXTENSION

I'm not convinced that this makes a lick of sense to users - but I think that we can live without for now, as long as we ....

>  say "user beware if triggering active tasks: they won't re-complete already-completed outputs".

Will look for this in the Docs PR then

2025-07-17 09:46 UTC, wxtim commented on cylc/flow/task_events_mgr.py
> +        # Useful debug but currently borks tests/f/cylc-message/02-multi.t:
IMO a line about why this currently borks tests?

2025-07-17 10:17 UTC, oliver-sanders commented
> PROPOSED PROPOSAL EXTENSION:

:facepalm: 

<br />

> respawn removed in-group children of any already-completed outputs of active group start tasks, with the associated prerequisites satisfied

Agreed, this is a blind-spot in the proposal (or at least a missing technical detail). In the spirit of the proposal, we would expect `b` to naturally follow `a` similar to how the Cylc 7 reset-to-waiting behaviour would have worked. I.E, the example should work the same for both `:started` and `:succeeded`. The difference between these cases is really just an internal implementation matter, somewhat related to https://github.com/cylc/cylc-flow/issues/6143.

Your suggestion is good, however, it could potentially have consequences outside of the group, e.g. respawning manually removed / suicide-triggered tasks / whatever. We could do with narrowing the scope of this to the tasks being triggered (i.e. the in-group tasks), here's two options:
1. Only spawn these outputs to tasks within the group (conceptually simple, but may be awkward to implement via the `spawn_on_output` interface).
2. If that's tricky, rather than spawning the outputs, we could spawn the in-group downstream tasks and get them to retrieve their prerequisites via https://github.com/cylc/cylc-flow/issues/6143.

<br />

> Suggest investigating as follow-up work, to avoid delaying this PR more. I have not thought through it yet.

Agreed, this is relatively niche and a behaviour. In this niche situation this will impact `:submitted`, `:started` and all custom outputs. Lets accept this minor flaw as is for now and address it at 8.6.0. 

<br />

> "user beware if triggering active tasks: they won't re-complete already-completed outputs".

Note, we're not re-completing the outputs of the active task (these outputs are still present in `itask.state.outputs` and persisted in the DB), more repeating the spawn event for internal consistency.

2025-07-17 12:42 UTC, wxtim commented on cylc/flow/scripts/trigger.py
> +Preparing, submitted, and running tasks can't be retrigged until finished.
I think this might confuse becuase tasks inside a sub-graph can be retriggered under these circumstances, and will be killed:
```suggestion
Tasks at the start of a retriggered sub-graph (including single tasks) cannot
be retriggered whilst in preparing, submitted, or running states.
```

P.S. Even if you disagree, check spelling of "retriggered".

2025-07-17 12:52 UTC, wxtim commented on cylc/flow/scripts/trigger.py
> +that would cause a stall.
I'm not sure my suggestion actually improves on your text, but I think it's worth a look.

I think that my problem with the orginal is using the term "Group trigger" implies something more special than "triggering >1 task".

I also think that it's worth being super clear about the differences between "start tasks" and tasks inside a sub-graph.

```suggestion
Trigger one or more tasks.

If used to trigger a group of tasks, Cylc will identify tasks
at the start of the sub-graph and start with these tasks.
Cylc trigger will erase the histories of the remaining tasks,
so that dependencies inside the group will be respected.
Dependencies outside the group triggered will be
satisfied to avoid a stall.
```

2025-07-17 12:58 UTC, wxtim commented on cylc/flow/scripts/trigger.py
> +        str(__doc__),
Why?

2025-07-17 13:29 UTC, wxtim commented on cylc/flow/scripts/remove.py
> +        str(__doc__),
Again, why?

2025-07-17 13:52 UTC, wxtim commented on tests/integration/test_task_pool.py
>          """Shorthand so only varible under test given as arg"""
```suggestion
def set_prereqs(prereqs):
"""Shorthand so only variable under test given as arg"""
schd.pool.set_prereqs_and_outputs(
```

2025-07-17 13:52 UTC, wxtim commented on tests/integration/test_task_pool.py
>          """Shorthand so only varible under test given as arg"""
```suggestion
        """Shorthand so only variable under test given as arg"""
```

2025-07-17 13:53 UTC, wxtim commented on tests/functional/spawn-on-demand/16-parents-yes-no/flow.cylc
> +        # Unstall, to see if foo gets spawned by baz at point 2.
```suggestion
        # Un-stall, to see if foo gets spawned by baz at point 2.
```

2025-07-17 13:54 UTC, wxtim commented on cylc/flow/scripts/trigger.py
> +  # trigger all failed tasks in workfow "test"
```suggestion
  # trigger all failed tasks in workflow "test"
```

2025-07-17 13:55 UTC, oliver-sanders commented on tests/unit/scripts/test_completion_server.py
> +    # $ cylc trigger --62656566<tab><tab>
This was testing that the completion moved onto the task argument after `--flow`, not `--flow=all`, we can just change `all` to something else:

```suggestion
    # $ cylc triger --flow=1 <tab><tab>
    assert await _complete_cylc('cylc', 'trigger', '--flow=1', '') == {
        'foo/run2//'
    }

    # $ cylc trigger --62656566<tab><tab>
```

2025-07-17 13:55 UTC, oliver-sanders commented on tests/unit/test_taskdef.py
> +    id_ = 'gargle-blaster'
:champagne: => :brain: :lemon: :bricks:

2025-07-17 13:55 UTC, oliver-sanders commented on tests/integration/scripts/test_back_compat_flow_all.py
> +    """blah"""
```suggestion
    """It should support the `all` argument from older client versions."""
```

2025-07-17 13:55 UTC, oliver-sanders commented on cylc/flow/scripts/trigger.py
> +that would cause a stall.
Agreed:

* No need to make "group trigger" a user-facing term, we should say "trigger a group of tasks".
* The command should have a simple one-line summary (note, a one line summary is also required by `cylc help all`).

2025-07-17 13:55 UTC, wxtim commented on tests/integration/test_xtrigger_mgr.py
>          assert foo.state.xtriggers['x']  # satisified
```suggestion
        assert foo.state.xtriggers['x']  # satisfied
```

2025-07-17 15:08 UTC, oliver-sanders commented on cylc/flow/scripts/trigger.py
> +that would cause a stall.
Also, remember that triggering one task is a more common use case than triggering a group of tasks, so we should bump the group-specific part of this down a bit to make the CLI help clearer to new users who are still learning the basics.

2025-07-17 15:15 UTC, wxtim commented
# Intra-version compatibility:


## Sending commands from 8.4.3 branch => workflow running this branch

|         | default | --flow=all | --flow=INT | --flow=none |
|---------|---------|------------|------------|-------------|
| remove  | ✅       | ✅          | ✅          |✅ *   |
| set     | ✅       | ✅          | ✅          | ✅           |
| stop    | ✅       | ✅*         | ✅*         | ✅*          |
| trigger | ✅       | ✅          | ✅          | ✅           |

## Sending commands from this branch => workflow running on 8.4.3

|         | default | --flow=all | --flow=INT | --flow=none |
|---------|---------|------------|------------|-------------|
| remove  | ✅       | ✅          | ✅          |✅ *   |
| set     | ✅       | ✅          | ✅          | ✅           |
| stop    | ✅       | ✅*         | ✅*         | ✅*          |
| trigger | ✅       | ✅          | ✅          | ✅           |


\* These fail both against this branch and master. Should not be fixed here.

2025-07-17 22:12 UTC, hjoliver commented
> Intra-version compatibility:

@wxtim - thanks for the thorough check there.  It looks like every passes - all I see is green ✅s - in which case I don't understand your comment \*-marked boxes and comment *\* These fail both against this branch and master. Should not be fixed here.* ??

2025-07-17 22:23 UTC, hjoliver commented
@wxtim - 

> I aim to please 😈

Your aim is true! 😁 

> I'm not convinced that this makes a lick of sense to users - but I think that we can live without for now, as long as we ....

Agreed, the explanation is pretty arcane, we need to just make it work intuitively.

And the workaround can be documented pretty clearly until then: *If you trigger an active task that has already completed some outputs, you'll need to manually set the already-completed outputs in downstream tasks...*

2025-07-18 00:09 UTC, hjoliver commented on cylc/flow/task_events_mgr.py
> +        # Useful debug but currently borks tests/f/cylc-message/02-multi.t:
Done, plus https://github.com/cylc/cylc-flow/issues/6857

2025-07-18 00:10 UTC, hjoliver commented on cylc/flow/scripts/trigger.py
> +Preparing, submitted, and running tasks can't be retrigged until finished.
Yep, you're right.

2025-07-18 00:12 UTC, hjoliver commented on cylc/flow/scripts/trigger.py
> +that would cause a stall.
Yep, agreed, dropping it down and rephrasing...

2025-07-18 00:29 UTC, hjoliver commented on cylc/flow/scripts/trigger.py
> +        str(__doc__),
I think my neovim setup was complaining about a typing issue there.  Not a good excuse. I'll revert and investigate.

2025-07-18 00:50 UTC, hjoliver commented on tests/functional/spawn-on-demand/16-parents-yes-no/flow.cylc
> +        # Unstall, to see if foo gets spawned by baz at point 2.
Not sure it matters, in a test, but OK!

2025-07-18 01:00 UTC, hjoliver commented on cylc/flow/scripts/trigger.py
> +that would cause a stall.
For clarity, I've tried to redo the CLI help by separately addressing single- and multi-task triggering. See what you think.

2025-07-18 01:01 UTC, hjoliver commented on cylc/flow/scripts/trigger.py
> +Preparing, submitted, and running tasks can't be retrigged until finished.
I've completely changed this bit, for an extensive help rewrite - see what you think.

2025-07-18 01:08 UTC, hjoliver commented
@oliver-sanders - 

> Your suggestion is good, however, it could potentially have consequences outside of the group, e.g. respawning manually removed / suicide-triggered tasks / whatever. We could do with narrowing the scope of this to the tasks being triggered (i.e. the in-group tasks), here's two options:
>
> -    Only spawn these outputs to tasks within the group (conceptually simple, but may be awkward to implement via the spawn_on_output interface).
> -    If that's tricky, rather than spawning the outputs, we could spawn the in-group downstream tasks and get them to retrieve their prerequisites via  https://github.com/cylc/cylc-flow/issues/6143.

Good we're on the same page here - you've actually repeated exactly what I suggested (albeit with useful extra detail), see *in-group children*: 

> respawn removed **in-group children** of any already-completed outputs of active group start tasks, with the associated prerequisites satisfied

> >  "user beware if triggering active tasks: they won't re-complete already-completed outputs".
> 
> Note, we're not re-completing the outputs of the active task (these outputs are still present in itask.state.outputs and persisted in the DB), more repeating the spawn event for internal consistency.

Agreed, that is what I meant, my phrasing was just a bit loose there, sorry. (Obviously "re-complete already completed outputs" doesn't make much literal sense, they can't be any more complete).

For the moment:
- follow-up issue: #6858 
- I've documented the workaround briefly in my reworked CLI help:

```
   How live (preparing, submitted, running) group members are handled:
  * live group start tasks are left to run - they already triggered
    WARNING: if they already completed outputs that other group tasks depend  <----- 
    on, you must manually satisfy ("cylc set") those prerequisites again      <-----
  * live tasks within the group tasks are killed, so that they can re-run in the flow
```

(see note on other comment above re "live" terminology)

2025-07-18 01:16 UTC, hjoliver commented on cylc/flow/scripts/trigger.py
> +that would cause a stall.
Note I've coined a new term "live tasks" for tasks with live jobs (or job scripts, at least) -  preparing, submitting, running -  since we can no longer call these "active tasks" and the full description is verbose as hell. If agreed I'll add it to the glossary...

2025-07-21 11:19 UTC, wxtim commented on cylc/flow/scripts/trigger.py
> +  * Attempts to live tasks (preparing, submitted, running) will be ignored.
The rest of this section reads really nicely - thank you!

```suggestion
  * Attempts to trigger live tasks (preparing, submitted, running) will be ignored.
```

2025-07-21 11:26 UTC, wxtim commented
>  These fail both against this branch and master. 

@hjoliver  - they fail, but the behaviour of your branch is identical to master.

> Should not be fixed here.

if we decide that a fix is required (it's probably not, becuase the number of users who will encounter this is miniscule, and it can be easily fixed by upgrading your command issuing version of Cylc) it should have it's own bug fix PR - I think getting this done and 8.5 out is higher priority.

2025-07-21 11:27 UTC, wxtim approved these changes
1 grammatical issue noted.

2025-07-21 17:08 UTC, oliver-sanders commented
I think we're there on the group trigger changes :tada:

But, unfortunately, I've gotta gripe with one of the off-topic changes, the change from triggering n=0 tasks in their assigned flows, to triggering tasks in all flows regardless.

This change is a regression of a recent bugfix https://github.com/cylc/cylc-flow/issues/6361 (we implemented the proposed behaviour wrong and had to fix it).

I get why you did this, without this change group-trigger had the potential to trigger group-start tasks in a different flow to their in-group downstreams which is odd in the extreme. In fact this behaviour is basically the same bug we were fixing with https://github.com/cylc/cylc-flow/issues/6361, so I accept the need for a change.

But the change to triggering n=0 tasks in all active flows is a problem for reflow use cases as it makes it much easier for the user to accidentally force flow-merging without asking for it. E.g, pressing the set/trigger button on any failed task will cause Cylc to merge in ALL active flow numbers as a side-effect (which is just confusing). If you're trying to wash over these tasks with a new flow, that could effectively disable reflow behaviour.

I've come up with a compromise solution which I hope you like. It preserves the old behaviour when triggering non-interdependent tasks, but extends this behaviour to provide a more sensible default for group-trigger use cases (where we are triggering groups of interdependent tasks).

* We take the tasks the user triggered and break them down into interdependent groups (i.e. groups of tasks for us to trigger in order).
* If there are any n=0 tasks in that group, we use the set of these flow numbers when triggering the group.
* We handle each group separately.

With this approach:

* We maintain the old status quo of not messing with an n=0 task's flow numbers unless the user asked us to.
* But all tasks in an interdependent group will trigger with the same flow numbers.
* Bonus, we can safely trigger n=0 tasks from different flows in the same operation without unexpected results.
* It's basically the proposed behaviour but extended from one task to many in order to accommodate group-trigger.

I've put it together here: https://github.com/hjoliver/cylc-flow/pull/68

(I haven't looked through the CLI/docs yet though, can do tomorrow)

2025-07-21 22:23 UTC, hjoliver commented
> I get why you did this, without this change group-trigger had the potential to trigger group-start tasks in a different flow to their in-group downstreams which is odd in the extreme. In fact this behaviour is basically the same bug we were fixing with https://github.com/cylc/cylc-flow/issues/6361, so I accept the need for a change.

Yep, that's exactly why I did it.

> I've come up with a compromise solution which I hope you like. ...

I do like it - good idea, thanks.

It could possibly be argued that only `n=0` group-start tasks should be counted as flow-defining, not group-internal ones (which get killed and removed), but I think either way is justifiable and in real scenarios it hardly matters.

2025-07-21 23:56 UTC, hjoliver commented
@oliver-sanders -  your side PR looks good except that it doesn't work for task glob inputs - hopefully that's a quick fix.

2025-07-22 12:37 UTC, wxtim commented on cylc/flow/scripts/trigger.py
> +  * Attempts to trigger live tasks (preparing, submitted, running) will be ignored.
```suggestion
  * Attempts to trigger live tasks (preparing, submitted, running) will be
    ignored.
```

2025-07-22 22:34 UTC, hjoliver commented
Merged your side-PR @oliver-sanders .

I've tweaked the trigger command help to explain flow assignment: 

```
Flow number assignment in triggered tasks:
  Active tasks (n=0) already have flows assigned; inactive tasks (n>0) do not.
  * If an interdependent group of triggered tasks includes active tasks, the
    flow will be assigned the existing flow numbers of those active tasks.
  * Otherwise the flow will be assigned all current active flow numbers.
```

There's a type annotation problem with your changes that I wasn't able to fix quickly - feel free to push the fix directly to this branch.

```
$ mypy cylc/flow
cylc/flow/commands.py:678: error: Need type annotation for "adjacency" (hint: "adjacency: Dict[<type>, <type>] = ...")  [var-annotated]
Found 1 error in 1 file (checked 212 source files)
```

2025-07-23 12:44 UTC, oliver-sanders commented
> There's a type annotation problem with your changes that I wasn't able to fix quickly - feel free to push the fix directly to this branch.

The `--flow` arg docs needed updating for the CLI/GUI, done in [2e6f541](https://github.com/cylc/cylc-flow/pull/6395/commits/2e6f5414c7c021846277170d870b21db1582c468).

@wxtim, please check this.

2025-07-23 12:57 UTC, wxtim commented
> > nch.
> 
> The `--flow` arg docs needed updating for the CLI/GUI, done in [2e6f541](https://github.com/cylc/cylc-flow/pull/6395/commits/2e6f5414c7c021846277170d870b21db1582c468).
> 
> @wxtim, please check this.

@oliver-sanders  Checked ✔️ 

Bandit failure seems unreasonable in the context?

2025-07-23 13:38 UTC, oliver-sanders commented
> Bandit failure seems unreasonable in the context?

Bandit has lost the plot! Added an ignore.

2025-07-23 14:05 UTC, oliver-sanders commented
[22e11f1](https://github.com/cylc/cylc-flow/pull/6395/commits/22e11f1ad226f62ef05cf490d02d1d717d51f562) should resolve the mypy issue.

2025-07-23 14:28 UTC, oliver-sanders commented
Tests passing!

2025-07-23 16:30 UTC, merged