Lint: Tell users that backslashes are no longer necessary after => & |
cylc/cylc-flow pull request #6459
Opened 2024-11-05 13:44 UTC by wxtim

Closes #6456 

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [ ] Changelog entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] This is a feature, but a lint feature, so suitable to be added to a maintainance release.

2024-11-18 15:58 UTC, MetRonnie commented on cylc/flow/scripts/lint.py
> +    },
I think this should be part of S014

2024-11-18 15:58 UTC, MetRonnie commented on changes.d/6459.feat.md
> +Cylc lint now checks for unecessary continuation characters in graph section.
```suggestion
`cylc lint` now checks for unecessary continuation characters in graph section.
```

2024-11-21 10:38 UTC, markgrahamdawson approved these changes

2024-11-21 20:38 UTC, hjoliver commented on cylc/flow/scripts/lint.py
> +    },
"more dead" 😁

2024-11-21 20:44 UTC, hjoliver requested changes
One typo detected and a couple of small tweaks suggested.

(It may be a bit picky, but I'd say "=>" *imply* line continuation rather than being line continuation).

2024-11-21 20:44 UTC, hjoliver commented on changes.d/6459.feat.md
> +`cylc lint` now checks for unecessary continuation characters in graph section.
```suggestion
`cylc lint` now checks for unnecessary continuation characters in the graph section.
```

2024-11-21 20:44 UTC, hjoliver commented on cylc/flow/scripts/lint.py
> +            '`=>` is a line continuation without `\\`'
```suggestion
            '`=>` implies line continuation without `\\`'
```

2024-11-21 20:44 UTC, hjoliver commented on cylc/flow/scripts/lint.py
> +            '`&` and `|` are line continuations without `\\`'
```suggestion
            '`&` and `|` imply line continuation without `\\`'
```

2024-11-22 09:00 UTC, hjoliver approved these changes

2024-11-22 09:43 UTC, merged

2024-11-25 11:00 UTC, MetRonnie commented
This has added a new lint rule S014 on 8.3.x, however S014 is already a different rule on master (https://github.com/cylc/cylc-flow/pull/6137), blocking sync PRs for the time being (https://github.com/cylc/cylc-flow/pull/6489). I think this should be reverted and re-opened against master.