cat-log: list out/err files when available via tailer
cylc/cylc-flow pull request #6480
Opened 2024-11-15 12:38 UTC by oliver-sanders

**Check List**

- [ ] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [ ] Contains logically grouped changes (else tidy your branch by rebase).
- [ ] Does not contain off-topic changes (use other PRs for other changes).
- [ ] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [ ] Tests are included (or explain why tests are not needed).
- [ ] Changelog entry included if this is a change that can affect users
- [ ] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [ ] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

2024-11-28 11:43 UTC, oliver-sanders commented
Note: This approach works just fine, however, it has a couple of small caveats:
* It isn't checking whether the out/err files have appeared in the output already reported - i.e. we could get duplicate `job.out` / `job.err` files in the output.
* The `job.out` and `job.err` files will always appear at the end, not in alphabetical order.

Ideally, we would avoid these caveats. I did start looking at a solution where I added the `job.out` and `job.err` files onto the end of the `mode` variable, e.g. `mode = list-dirs:job.out:job.err`, that way they can be output along with the regular directory listing in a much more elegant way.

But I ran out of time. Writing this up in case anyone else needs to take this one over.

2025-01-29 13:22 UTC, wxtim commented on tests/functional/cylc-cat-log/12-remote-out-err-tailer.t
`12-delete-kill.t` already exists - can we make this number 13?

2025-01-29 13:47 UTC, wxtim approved these changes
- [x] Read code
- [x] Ran new test
- [x] Tried manually testing, including looking at available log files in TUI before and after.
- [x] Ran new test with coverage. Lines indicated in the diff were covered.

2025-02-05 15:48 UTC, MetRonnie requested changes

2025-02-05 15:48 UTC, MetRonnie commented on cylc/flow/scripts/cat_log.py
> +                out, err = proc.communicate()
This is now swallowing stderr and non-zero exit codes (discussed in-person)

2025-02-05 16:02 UTC, MetRonnie commented on cylc/flow/scripts/cat_log.py
> +                print(err, file=sys.stderr)
Currently on 8.4.0 the `cat-log -m l` command exits non-zero if this subprocess exits non-zero. But it no longer does on this branch

2025-02-05 16:17 UTC, oliver-sanders commented on cylc/flow/scripts/cat_log.py
> +                print(err, file=sys.stderr)
Hopefully fixed.

2025-02-11 15:04 UTC, MetRonnie commented on cylc/flow/scripts/cat_log.py
> +                out, err = proc.communicate()
I think we need to include the `proc.communicate()` in the suppressing of the `KeyboardInterrupt`

2025-02-13 18:22 UTC, MetRonnie commented on cylc/flow/scripts/cat_log.py
> +                out, err = proc.communicate()
If the whole `if isinstance` block is included in the `suppress` block, it avoids traceback on ctrl+c. But not that important I guess

2025-02-13 19:16 UTC, MetRonnie approved these changes
Take or leave my KeyboardInterrupt suggestions

2025-02-14 09:34 UTC, oliver-sanders commented
> Take or leave my KeyboardInterrupt suggestions

I think we need to do more than just swallow the traceback. Have opened a low-priority issue: https://github.com/cylc/cylc-flow/issues/6609

2025-02-14 09:35 UTC, oliver-sanders commented on cylc/flow/scripts/cat_log.py
> +                out, err = proc.communicate()
The traceback is a cosmetic problem, but I think there are pre-existing functional issues here, https://github.com/cylc/cylc-flow/issues/6609

2025-02-14 09:36 UTC, merged