Lint.6456.fewer line continuations
cylc/cylc-flow pull request #6493
Opened 2024-11-25 11:17 UTC by wxtim

Replaces https://github.com/cylc/cylc-flow/pull/6459 which blocks sync PRs

Otherwise the same diff.

Seealso @MetRonnie's Comment on https://github.com/cylc/cylc-flow/pull/6459#issuecomment-2497686715

2024-11-25 12:39 UTC, MetRonnie commented on changes.d/6459.feat.md
6493

2024-11-25 12:41 UTC, oliver-sanders commented on changes.d/6459.feat.md
It's ok to reference the issue rather than the PR right?

2024-11-25 13:11 UTC, MetRonnie commented on changes.d/6459.feat.md
Might be better in this case

2024-11-25 21:00 UTC, hjoliver requested changes

2024-11-25 21:00 UTC, hjoliver commented on cylc/flow/scripts/lint.py
> +            '`=>` is a line continuation without `\\`.'
```suggestion
            '`=>` implies line continuation without `\\`.'
```
(Pretty sure you accepted this change on the original!)

2024-11-26 22:46 UTC, hjoliver approved these changes
All good 🎉

2024-11-26 22:47 UTC, merged

2024-11-27 13:48 UTC, MetRonnie commented on changes.d/6459.feat.md
#6497